### ISSUE TITLE
overwrite (-force, -f) does not have any effect

### ISSUE THREAD

**Issue by pgawle** [pornel/pngquant#10]
Hi, 

I'm trying to use "improved-pngquant" in my build script. I was looking for a way to overwrite old file with a new (compressed) file. 

I found out thru "-h" option that there is a -f option but that does not have any effect and I'm still getting default extension "-fs8". 

Is there any work around on that?

**Comment by bfayers** [comment]
I don't like to re-open such old issues like this, however this 
`-f --ext .png` 
no longer works, or atleast I can't get it to. I am running
 `pngquant -f --ext .png --quality 65-80 --strip --skip-if-larger vlc_2017-07-08_13-50-41.png vlc_2017-07-08_13-50-41.png` 
and the result is `error: cannot open .png for reading`

**Comment by pornel** [comment]
Fixed in b526af94ca3c116239739b8e2ec194bad54926f8
