### ISSUE TITLE
Add some test application for libimagequant

### ISSUE THREAD

**Issue by zedxxx** [pornel/pngquant#101]
Please, add some test app like `test-libimagequant.exe` for check lib functionality. Since you don't distribute precompiled version of your library, it would be useful to have a utility for testing the library after compilation.

**Comment by pornel** [comment]
Here's a simple example app in C:

https://github.com/ImageOptim/libimagequant/blob/f54d2f1a3e1cf728e17326f4db0d45811c63f063/example.c

and C#:

https://github.com/ImageOptim/libimagequant/blob/f54d2f1a3e1cf728e17326f4db0d45811c63f063/libimagequant.cs

and a fancier example in Rust:

https://github.com/ImageOptim/gifski/blob/418de5ab90973f41901e0d55a67e7c199d359ada/src/lib.rs#L133-L157
