### ISSUE TITLE
Compilation problem on Android

### ISSUE THREAD

**Issue by maartenvandillen** [pornel/pngquant#106]
Hi I am trying to compile pngquant on Android using NDK r10 (64bit) on OS X.
The problem I am having is that the error about adding the -std=c99 flag is showing. When adding that switch in my Android.mk file it complains about being for C, not C++ (warning: command line option '-std=c99' is valid for C/ObjC but not for C++). The libimagequant file clearly is cpp, so please explain to me how this switch would affect compiling the project? All the other C files compile just fine, with or without the switch.

Any help is really appreciated.

Thanks,
Maarten van Dillen

**Comment by Drjacky** [comment]
@maartenvandillen Is that possible to share the built library for Android?
And maybe, with the usage explanation.

Thanks 🙏

**Comment by maartenvandillen** [comment]
@Drjacky No sorry, this was back in 2014 and I have a new laptop now.
