### ISSUE TITLE
Using libimagequant without libpng or zlib.

### ISSUE THREAD

**Issue by HMVC0** [pornel/pngquant#110]
I am trying to use libimagequant to compress png files produced by gdi plus screen capture program (written in c++ on visual studio 2013). The only library i use is libimagequant and i don't intend to use another library in my program.
So, is it possible to write the png to a file without using libpng unlike pngquant.

**Comment by pornel** [comment]
An example is here:

https://github.com/ImageOptim/libimagequant/blob/f54d2f1a3e1cf728e17326f4db0d45811c63f063/example.c
