### ISSUE TITLE
[enhancement] build with shared libraries  instead static 

### ISSUE THREAD

**Issue by sergiomb2** [pornel/pngquant#128]
Hi, 
Fedora rules says that we should be compiled everything with shared libraries. And normally we disable static and remove static libs .
So we have this patch 
http://pkgs.fedoraproject.org/cgit/pngquant.git/tree/pngquant-2.3.0_fix-Makefile.patch
that make pngquant generate shared libraries and compile with it . 
I don't have time to do a better patch to apply to your code , but feel free to use it .

**Comment by pornel** [comment]
#138 #146
