### ISSUE TITLE
SIGSEGV on specially crafted png - ab9f6ec5

### ISSUE THREAD

**Issue by jodiecunningham** [pornel/pngquant#136]
Hi pornel,

Through some fuzzing I found a file that would cause this software to segfault. 

Source file:
![ab9f6ec5](https://cloud.githubusercontent.com/assets/1390085/5996016/7df98152-aa65-11e4-9b99-a4c88129769e.png)
also found on https://www.dropbox.com/s/u72bfcir24o9iyd/ab9f6ec5?dl=0

Reproduce:
    pngquant ab9f6ec5 -o /dev/null -f

Output:
    Aborted

BT (filename was different in BT for this one):
```
[New LWP 11074]
Core was generated by `/home/jodicun/opt/pngquant/pngquant ../fuzzer1422851548/crashes/id:000000,sig:1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35      ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
#1  0x00000000004074b3 in memcpy (__len=0x1f2000d, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
#2  read_chunk_callback (png_ptr=<optimized out>, in_chunk=0x642828) at rwpng.c:163
#3  0x00007ffff7bbdf51 in ?? () from /lib/x86_64-linux-gnu/libpng12.so.0
#4  0x00007ffff7bc4a01 in png_read_info () from /lib/x86_64-linux-gnu/libpng12.so.0
#5  0x00000000004083ad in rwpng_read_image24_libpng (infile=0x642130, mainprog_ptr=0x7fffffffd780, verbose=<optimized out>) at rwpng.c:218
#6  0x0000000000405a8c in read_image (options=0x6420b0, filename=0x7fffffffe2d5 "../fuzzer1422851548/crashes/id:000000,sig:11,src:000000,op:havoc,rep:8", using_stdin=<optimized out>, input_image_p=0x7fffffffd780, liq_image_p=0x7fffffffd770, keep_input_pixels=<optimized out>, verbose=0x0) at pngquant.c:797
#7  0x0000000000405cde in pngquant_file (filename=filename@entry=0x7fffffffe2d5 "../fuzzer1422851548/crashes/id:000000,sig:11,src:000000,op:havoc,rep:8", outname=outname@entry=0x7fffffffe31f "/dev/null", options=options@entry=0x7fffffffde50) at pngquant.c:556
#8  0x0000000000403c90 in main (argc=<optimized out>, argv=<optimized out>) at pngquant.c:506
#9  0x00007ffff7509ec5 in __libc_start_main (main=0x4020e0 <main>, argc=0x5, argv=0x7fffffffe068, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe058) at libc-start.c:287
#10 0x0000000000404d82 in _start ()
exe = '/home/jodicun/opt/pngquant/pngquant ../fuzzer1422851548/crashes/id:000000,sig:1'
```

Valgrind:
```
==20210== Use of uninitialised value of size 8
==20210==    at 0x572B88F: crc32 (in /lib/x86_64-linux-gnu/libz.so.1.2.8)
==20210==    by 0x4E3AD6C: ??? (in /lib/x86_64-linux-gnu/libpng12.so.0.50.0)
==20210==    by 0x4E41047: ??? (in /lib/x86_64-linux-gnu/libpng12.so.0.50.0)
==20210==    by 0x4E47A00: png_read_info (in /lib/x86_64-linux-gnu/libpng12.so.0.50.0)
==20210==    by 0x4083AC: rwpng_read_image24_libpng (rwpng.c:218)
==20210==    by 0x405A8B: read_image (pngquant.c:797)
==20210==    by 0x405CDD: pngquant_file (pngquant.c:556)
==20210==    by 0x403C8F: main (pngquant.c:506)
```

Version tested:
Git checkout cc39b47799a7ff2ef17b529f9415ff6e6b213b8f ( Dec 12 2014 ) 

System Details:
AMD64
Distributor ID: Ubuntu
Description: Ubuntu 14.04.1 LTS
Release: 14.04
Codename: trusty

Found with the fuzzer American Fuzzy Lop ( http://lcamtuf.coredump.cx/afl/ )

**Comment by jodiecunningham** [comment]
Looks like this is fixed on the latest git pull, closing!

**Comment by pornel** [comment]
Thanks for fuzzing it!

The crash happens in https://github.com/pornel/pngquant/blob/cc39b47799a7ff2ef17b529f9415ff6e6b213b8f/rwpng.c#L163

```c
memcpy(chunk->data, in_chunk->data, in_chunk->size);
```

where `in_chunk` is given by libpng, and from the stack trace it looks like the length was completely wrong, so it may be a vulnerability in libpng itself.

**Comment by jodiecunningham** [comment]
I dug just a little more into this. The fuzzer was running with a memory limit of 50MB. (`ulimit -Sv 50000`)
While running this through ImageMagick ,  IM only used 5MB of RAM. But for some reason, pngquant is using 36+MB for the same image. The full valgrind has it looping over that "==20210== Use of uninitialised value of size 8" block over 10,000 times, after which valgrind gives up tracking it.

Running with the ulimit will crash, but running with the memory set to unlimited completes with just an error. The memory usage is still pretty curious.

**Comment by pornel** [comment]
This is because in your example pngquant is told to keep a chunk that is 32636941 bytes large.
