### ISSUE TITLE
pngquant 2.3.4: Makefile doesn't create bin/ dir before attempting to move files to it

### ISSUE THREAD

**Issue by vanastassiou** [pornel/pngquant#137]
Re pngquant 2.3.4

Ran `./configure --prefix=/custom/directory`, but `make install` got me:

    install -m 0755 -p pngquant /custom/directory/bin/pngquant
    install: cannot create regular file `/custom/directory/bin/pngquant': No such file or directory
    make: *** [install] Error 1
Checked out `Makefile`, wasn't able to see anything meant to create the directory `$(BIN) $(BINPREFIX)/$(BIN)` before installing to it.

Can work around it by manually creating the `bin` directory and running `make install` again.

**Comment by pornel** [comment]
Thanks. Hopefully fixed
