### ISSUE TITLE
Incredible. Thank you

### ISSUE THREAD

**Issue by unsalkorkmaz** [pornel/pngquant#139]
This is just incredible. Huge difference with other png optimization programs. I just wanted to thank you. :bow: 

Edit: Just a suggestion;
In http://pngquant.org/php.html we need to define those values before shell_exec for filenames in non-latin languages:
$locale = 'en_US.UTF-8';
setlocale(LC_ALL, $locale);
putenv('LC_ALL='.$locale);

it seems php execute by default the command with LOCALE=C. 
http://php.net/manual/en/function.shell-exec.php#78279

**Comment by pornel** [comment]
Thanks. 

Locale are troublesome, so I'd rather leave them out of scope, e.g. invalid UTF-8 is allowed on file system level, but not by all locale.

**Comment by unsalkorkmaz** [comment]
Ok. I had problems with non-latin filenames and that was solution. Thats it. Thanks for program again :)

**Comment by unsalkorkmaz** [comment]
Can you suggest a good jpg optimization program like pngquant for png? (sorry, totally off-topic)

**Comment by bluenlive** [comment]
I recommend mozjpeg.
It's being developed by Mozilla Foundation.

https://github.com/mozilla/mozjpeg
