### ISSUE TITLE
Segfault/crash with PNGs where width and/or height is < 3px

### ISSUE THREAD

**Issue by markostamcar** [pornel/pngquant#14]
Happens on Linux (compiled by someone else):

pngquant, version 1.7.2 (February 2012), by Greg Roelofs, Kornel Lesinski.
   Compiled with SSE2 instructions.
   Compiled with libpng 1.2.46; using libpng 1.2.46.
   Compiled with zlib 1.2.3.4; using zlib 1.2.3.4.

and Windows (binary from the website):

pngquant, version 1.7.2 (February 2012), by Greg Roelofs, Kornel Lesinski.
   Compiled with libpng 1.2.37; using libpng 1.2.37.
   Compiled with zlib 1.2.3; using zlib 1.2.3.

I know, I know, why would you want to optimize such small PNGs? Well, they are part of a batch job of 1000s of differently sized PNGs.

**Comment by fotografi** [comment]
>
