### ISSUE TITLE
Can't write an image if set to overwrite the original image

### ISSUE THREAD

**Issue by AmperAndSand** [pornel/pngquant#140]
I'm getting this error message:

    writing 256-color image as C:\sample_directory\Clipboard01.png
    error: failed writing image to C:\sample_directory\Clipboard01.png
    There were errors quantizing 1 file out of a total of 1 file.

...if I set pngquant to overwrite the original image (and use the same name as the original image) with the processed one. 

The command line arguments I use are:

`--verbose --skip-if-larger --force --ext .png --speed 1 --quality=85-100`

This is in Windows 7, 64-bit. I'm using the v2.3.1 binaries. Anyone know of a workaround? 

I would like to use the same name as the original so I can easily follow it up in the batch file with OptiPNG and AdvanceCOMP, in that order (both are also set to overwrite the original PNG image with the recompressed version).

**Comment by hachigoro** [comment]
I have the same issue. I use the same flags as you and I'm also in Windows 7 64 bit. I double checked that the files are not read only. I have also tried using the --output flag with the same file name, but I get the same error. 

Thanks for your work!

**Comment by hachigoro** [comment]
I did some more research, and it seems that the "rename" function (pngquant.c line 760) does not work properly in Windows (works fine in Linux). If the target file already exists, most of the time (not always) it won't be able to replace it.

This behaviur is documented here: https://www.securecoding.cert.org/confluence/display/cplusplus/FIO10-CPP.+Take+care+when+using+the+rename()+function

And also here http://stackoverflow.com/questions/11021639/overwriting-files-in-windows-by-renaming-randomly-fails

The solution is, if the target file already exists, first remove it, then call rename. To be safe you can create a backup of the target file before removing it just in case rename fails.

**Comment by pornel** [comment]
Thanks for investigating that. I'll add unlink for Windows.

**Comment by moazam1** [comment]
Noticed you fixed this issue but binary files are still not up to date.
