### ISSUE TITLE
CronTab and Pngquant

### ISSUE THREAD

**Issue by sinofanger** [pornel/pngquant#141]
I have created a small script to compress all the images using pngquant. The script is as follows:

    #!/bin/bash
    find /home/ghosthut/wp-content/uploads -mtime -2 -iname '*.png' -print0 | xargs -0 pngquant --quality=65-80 --ext .png --force 256
    chmod -R 777 /home/ghosthut/wp-content/uploads

This script is localted at /usr/local/optimize2.sh It runs correctly when executed via SSH. It compresses all the png images in the mentioned directory. But when tried to run via Crontab, it return the error ***xargs: pngquant: No such file or directory*** inside the log file.

The crontab entry (I use **crontab -e** as root user) for running this script is:

    43 03 * * * /usr/local/optimize2.sh > /var/log/cron.log 2>&1

*PS - I have other entries in my crontab as well which get executed correctly. Only this entry regarding pngquant returns this error. Here is a screenshot of my crontab:*
![enter image description here][1]

  [1]: http://i.stack.imgur.com/piGLq.png

**Comment by pornel** [comment]
Crontabs require `PATH` specified. It's not unique to pngquant.
