### ISSUE TITLE
What's the default quality?

### ISSUE THREAD

**Issue by mahemoff** [pornel/pngquant#142]
What's the default quality level, ie what min and max are used if --quality is not included?

Can this be added to the docs?

**Comment by pornel** [comment]
The default behavior is equivalent to `--quality=0-100`

**Comment by mahemoff** [comment]
Okay thanks Kornel. You might want to add it to the README/man page as it's not explicitly stated as the default, e.g. "If this isn't provided, the quality isn't constrained, i.e. it's equivalent to setting `--quality=0-100`.

I guess it became more obvious this is the default once I re-read the quality flag docs to understand what the quality flag means, but it took me a bit by surprise as as I initially assumed quality was the same as jpeg-style "set image to this quality".
