### ISSUE TITLE
How to use in iOS ? 

### ISSUE THREAD

**Issue by Joezbx** [pornel/pngquant#145]
I would like to optimize png before upload to server in ios,  I have tried using the libimagequant but got a error png image .
Perhaps my code is error...
Any suggestions for me , Thanks.

    CGImageRef baseImage = [image CGImage];
    int width = image.size.width;
    int height= image.size.height;
    
    CGColorSpaceRef space = CGColorSpaceCreateDeviceRGB();
    unsigned char *rawData = (unsigned char*) calloc(height * width * 4, sizeof(unsigned char));
    CGContextRef ctx = CGBitmapContextCreate(rawData, width, height, 8, width*4, space, kCGImageAlphaPremultipliedLast|kCGBitmapByteOrder32Big);
    CGColorSpaceRelease(space);
    CGContextDrawImage(ctx, CGRectMake(0, 0, width, height), baseImage);
    CGContextRelease(ctx);
    
    liq_attr *liqAttr = liq_attr_create();
    liq_set_quality(liqAttr,10, 20);
    liq_set_max_colors(liqAttr,2);
    liq_image *liqImage = liq_image_create_rgba(liqAttr, rawData, (int)width, (int)height, 0);
    liq_result *liqRes = liq_quantize_image(liqAttr, liqImage);
    
    if ( liqRes ) {
        int size = (int)width*height;
        liq_write_remapped_image(liqRes, liqImage, rawData, size);
    }
    
    liq_attr_destroy(liqAttr);
    liq_image_destroy(liqImage);
    liq_result_destroy(liqRes);
    
    NSData *data = [NSData dataWithBytes:rawData length:4 * width * height];
    
    NSString *docsDir;
    NSArray *dirPaths;
    
    dirPaths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
    docsDir = [dirPaths objectAtIndex:0];
    NSString *databasePath = [[NSString alloc] initWithString: [docsDir stringByAppendingPathComponent:@"foo.png"]];
    [data writeToFile:databasePath atomically:YES];

**Comment by pornel** [comment]
Please note that `libimagequant` does not support PNG or any compressed image format at all. It creates raw data that you need to pass to a file-format-specific library.

**Comment by Joezbx** [comment]
It mean's i should init lib_image with bitmap ?

**Comment by pornel** [comment]
To write a png either copy rwpng.c from pngquant or use http://lodev.org/lodepng/

**Comment by maxs15** [comment]
@Joezbx did you succeed ?
An example would be much appreciated :)

**Comment by jtressle** [comment]
@maxs15 @pornel @Joezbx Here's my working example to use pngquant in ios.  I used lodepng to convert from libimagequant back to png:

UIImage to RGBA:

`-(NSData *) rgbaFromImage:(UIImage *)image
{
    CGImageRef imageRef = image.CGImage;
    
    _bitsPerPixel           = CGImageGetBitsPerPixel(imageRef);
    _bitsPerComponent       = CGImageGetBitsPerComponent(imageRef);
    _width                  = CGImageGetWidth(imageRef);
    _height                 = CGImageGetHeight(imageRef);
    _bytesPerRow            = CGImageGetBytesPerRow(imageRef);
    CGBitmapInfo bitmapInfo = kCGImageAlphaPremultipliedLast;
    
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    
    unsigned char *bitmapData = (unsigned char *)malloc(_bytesPerRow * _height);
    
    CGContextRef context = CGBitmapContextCreate(bitmapData,
                                                 _width,
                                                 _height,
                                                 _bitsPerComponent,
                                                 _bytesPerRow,
                                                 colorSpace,
                                                 bitmapInfo);
    
    CGColorSpaceRelease(colorSpace);
    
    //draw image
    CGContextDrawImage(context, CGRectMake(0, 0, _width, _height), imageRef);
    
    //free data
    CGContextRelease(context);
    
    //create NSData from bytes
    NSData *data = [[NSData alloc] initWithBytes:bitmapData length:_bytesPerRow * _height];
    
    //check if free is needed
    free(bitmapData);
    
    return data;
}`

RGBA -> LibImageQuant -> PNG Data

`-(NSData *) quantizedImageData:(NSData *)data
{
    unsigned char *bitmap = (unsigned char *)[data bytes];
    
    unsigned char **rows = (unsigned char **)malloc(_height * sizeof(unsigned char *));
    
    for (int i = 0; i < _height; ++i)
    {
        rows[i] = (unsigned char *)&bitmap[i * _bytesPerRow];
    }
    
    //create liq attribute
    liq_attr *liq = liq_attr_create();
    liq_set_speed(liq, _speed);
    
    liq_image *img = liq_image_create_rgba_rows(liq,
                                                (void **)rows,
                                                (int)_width,
                                                (int)_height,
                                                _gamma);
    
    if (!img)
    {
        NSLog(@"error creating image");
    }
    
    liq_result *quantization_result;
    if (liq_image_quantize(img, liq, &quantization_result) != LIQ_OK)
    {
        NSLog(@"error liq_image_quantize");
    }
    
    // Use libimagequant to make new image pixels from the palette
    bool doRows = (_bytesPerRow / 4 > _width);
    size_t scanWidth = (doRows) ? (_bytesPerRow / 4) : _width;
    
    //create output data array
    size_t pixels_size = scanWidth * _height;
    unsigned char *raw_8bit_pixels = (unsigned char *)malloc(pixels_size);
    
    liq_set_dithering_level(quantization_result, 1.0);
    
    if (doRows)
    {
        unsigned char **rows_out = (unsigned char **)malloc(_height * sizeof(unsigned char *));
        for (int i = 0; i < _height; ++i)
            rows_out[i] = (unsigned char *)malloc(scanWidth);
        
        liq_write_remapped_image_rows(quantization_result, img, rows_out);
        
        //copy data to raw_8bit_pixels
        for (int i = 0; i < _height; ++i)
            std::memcpy(raw_8bit_pixels + i*(scanWidth), rows_out[i], scanWidth);
        
        free(rows_out);
    }
    else
    {
        liq_write_remapped_image(quantization_result, img, raw_8bit_pixels, pixels_size);
    }
    
    const liq_palette *palette = liq_get_palette(quantization_result);
    
    //save convert pixels to png file
    LodePNGState state;
    lodepng_state_init(&state);
    state.info_raw.colortype = LCT_PALETTE;
    state.info_raw.bitdepth = 8;
    state.info_png.color.colortype = LCT_PALETTE;
    state.info_png.color.bitdepth = 8;
    
    for (size_t i = 0; i < palette->count; ++i)
    {
        lodepng_palette_add(&state.info_png.color, palette->entries[i].r, palette->entries[i].g, palette->entries[i].b, palette->entries[i].a);
        
        lodepng_palette_add(&state.info_raw, palette->entries[i].r, palette->entries[i].g, palette->entries[i].b, palette->entries[i].a);
    }
    
    unsigned char *output_file_data;
    size_t output_file_size;
    
    unsigned int out_state = lodepng_encode(&output_file_data,
                                            &output_file_size,
                                            raw_8bit_pixels,
                                            (int)_width,
                                            (int)_height,
                                            &state);
    
    if (out_state)
    {
        NSLog(@"error can't encode image %s", lodepng_error_text(out_state));
    }
    
    NSData *data_out = [[NSData alloc] initWithBytes:output_file_data length:output_file_size];
    
    liq_result_destroy(quantization_result);
    liq_image_destroy(img);
    liq_attr_destroy(liq);
    
    free(rows);
    free(raw_8bit_pixels);
    
    lodepng_state_cleanup(&state);
    
    return data_out;
}`
