### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by docal56** [pornel/pngquant#148]
Hi, I am getting the following error when I try to run grunt watch: 

dyld: lazy symbol binding failed: Symbol not found: _node_module_register

I'm on an iMac running OS X Yosemite v: 10.10.2

Could you help please? 
Thanks :)

**Comment by pornel** [comment]
Sorry, I can't help, because this is not related to pngquant tool specifically, but one of the node wrappers/grunt plugins built around it.

**Comment by docal56** [comment]
Ok thanks, could you point me into the direction of where I might be able to get some help please? :) 





—

**Comment by pornel** [comment]
Try reporting it to author of the grunt plugin you've installed.

**Comment by docal56** [comment]
Thanks - a colleague has sorted it :) 


—
