### ISSUE TITLE
DEB File creation Error

### ISSUE THREAD

**Issue by semaf** [pornel/pngquant#149]
If i am trying to create the Deb File I am getting errors that % are not allowed.

0 -  Maintainer: [ root ]
1 -  Summary: [ PNG quantization tool for reducing image file size ]
2 -  Name:    [ pngquant ]
3 -  Version: [ 2.3.5 ]
4 -  Release: [ 1%{?dist} ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ pngquant ]
9 -  Alternate source location: [  ]
10 - Requires: [ libpng%{?_isa} >= 1.2.46-1
zlib%{?isa} >= 1.2.3-1 ]
11 - Provides: [ pngquant ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

Release and Requires are getting this characters.

**Comment by pornel** [comment]
How are you creating the deb file?

Have you tried the official one? https://packages.debian.org/jessie/pngquant

**Comment by pornel** [comment]
Closing due to lack of information
