### ISSUE TITLE
Wrong commit tagged with 2.4.0

### ISSUE THREAD

**Issue by toy** [pornel/pngquant#152]
Tag 2.4.0 points to 0c123f88e633e1c77f4712fb96a111ab3e7cbc84 which has old (2.3.6) version numbers. It should be 8c84f98ec5656f3cf194b6da6a61129bb6c320c7 or 1af4d6077ce0e4949b0de9ce5001ecaace8698ec.

**Comment by pornel** [comment]
I know, sorry. I'm sticking to tags being immutable forever, so I'll fix that in 2.4.1.

**Comment by toy** [comment]
Don't be sorry, such things happen. And I totally agree that changing tags is bad. I've noticed this as in my project I'm building multiple binaries from sources and the first check after successful compilation is presence of expected version in executable help output.

**Comment by sergiomb2** [comment]
Could you tag 2.4.0.1 with 2.4.0 ? I prefer have correct tags ... ,  if someone want package it, will be more simpler , I think .
Thanks,

**Comment by pornel** [comment]
Done

**Comment by sergiomb2** [comment]
Hi, just drop a note that github let you delete a tag, so it is possible retag a version ... I just did .

**Comment by pornel** [comment]
I know it's possible, but I consider this inappropriate. Tag is supposed to be a permanent indicator, so nobody has to ever wonder whether they have "old tag" or "new tag".
