### ISSUE TITLE
 error: rwpng_read_image() error 25

### ISSUE THREAD

**Issue by iwanbk** [pornel/pngquant#154]
Hello,

Thanks for this great project, it is a big help in my project.
Recently i got this error in some of my .png images
```
 error: rwpng_read_image() error 25
```
When i check pngquant code, it seems that the error come from libpng.
Is it mean it is not valid .png image?

FYI:
- Chrome and simple image viewer can display the image.
- I also tried to compress the image using tinypng.com, it said : "Image appears corrupt"

Thanks

**Comment by iwanbk** [comment]
Another info : i use pngquant binary from latest git version.

**Comment by polym** [comment]
+1
```
  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.5.21)
      zlib: shared (1.2.8)
     lcms2: no

```

**Comment by iwanbk** [comment]
I have added `-v` option, you can find error messages below
```
error: Read error
  error: rwpng_read_image() error 25
There were errors quantizing 1 file out of a total of 1 file
```

**Comment by pornel** [comment]
The error 25 means libpng can't read it, probable because the file is corrupt. There's nothing pngquant can do about it. Load and re-save the image in a graphics program to fix it.

**Comment by pornel** [comment]
I've changed the error message to be more user-friendly though.
