### ISSUE TITLE
Differences between site and command line

### ISSUE THREAD

**Issue by MoonDevilzzz** [pornel/pngquant#156]
Hi guys!
Pretty good script!
But i have some issue,
![spec-catalog-title-icon](https://cloud.githubusercontent.com/assets/2973768/7871824/254d87a6-059b-11e5-99c4-9f5b0995a104.png)
I compressed this file by command line (pngquant  *.png) and it has 18Kb size instead of 24Kb, but if i compress it again on https://tinypng.com/ its only 400 bytes at all.I suppose tinypng are using pngquant?
Then why so much output size difference?

**Comment by pornel** [comment]
I can't reproduce it. 

pngquant 2.3.5 generates file that is 219 bytes large.

**Comment by MoonDevilzzz** [comment]
I have 2.4.1 version is installed, where can i get 2.3.5 for CentOS 6?I hope it will solve may problem :)

**Comment by MoonDevilzzz** [comment]
Dude!I catch it!
Version 2.0.0 do the 207 bytes file!
Whats wrong with newest?

**Comment by pornel** [comment]
Oh, you have libpng 1.2. That's the problem. It's an old crappy buggy version. Use 1.6 or later.

**Comment by pornel** [comment]
Another idea - maybe it chooses palette wrong and dithering bloats the file. Do you get small file with --nofs?

**Comment by pornel** [comment]
OK, I've found it. It's not a bug, it's a feature! :D

The file has 19KB of metadata. pngquant with libpng new enough can preserve metadata.

![screen shot 2015-05-31 at 23 45 10](https://cloud.githubusercontent.com/assets/72159/7904071/13bd8cc4-07ef-11e5-8b59-3423abc108b4.png)

**Comment by MoonDevilzzz** [comment]
:dancer: 
How can we prevent preserving meta?

**Comment by pornel** [comment]
Run ImageOptim or `pngcrush -rem alla` that does the removal.
