### ISSUE TITLE
Color shift in images

### ISSUE THREAD

**Issue by agross** [pornel/pngquant#157]
I've got a couple of images that get a weird yellowish/reddish shift as soon as I use pngquant to minify them:

```
pngquant --force -v --output test.png me.png
```

![2015-06-01_00-02-59](https://cloud.githubusercontent.com/assets/16245/7904158/b3d03836-07f1-11e5-8ad7-c04fd2807473.png)

(Chrome and Firefox show the shift, while IE does not.)

You can download the source image [here](https://www.dropbox.com/s/cckpjueat1w6fli/alexander-gross.png?dl=0).

Any ideas what might cause this?

**Comment by pornel** [comment]
Sorry, I'm unable to reproduce the issue. In all browsers I have (Chrome and Safari on OS X as well as Firefox and IE on Windows 10) it displays without the yellow shift.

The image doesn't have any color profile information, so theoretically it's undefined and could be interpreted as using monitor's profile. 

pngquant interprets unlabelled files as having sRGB gamma 2.2, same as most modern web browsers, and when it writes files it explicitly puts sRGB tag.

Try ImageOptim or some optimizer that strips metadata from PNG and see if that helps. If so, then your browser is doing some weird color management.

**Comment by agross** [comment]
Thanks, that pointed me in the right direction. My main display had an ICM profile assigned. After removing it and restarting Chrome, the yellowish tint was removed from the pngquant'ed images.
