### ISSUE TITLE
Strange atrifacts with speed5 or lower

### ISSUE THREAD

**Issue by myarashevich** [pornel/pngquant#158]
Checked on 2.4.1,  2.3.1.
original
![original](https://cloud.githubusercontent.com/assets/2477998/7933933/b1467716-092b-11e5-8c9d-c73fa84e643c.png)
--speed 5
![speed5](https://cloud.githubusercontent.com/assets/2477998/7933945/bd451180-092b-11e5-9a1b-a8c5aa001c2a.png)
--speed 6
![speed6](https://cloud.githubusercontent.com/assets/2477998/7933949/c480870e-092b-11e5-8e8c-e415c50010f9.png)

**Comment by myarashevich** [comment]
Images on dropbox just in case
https://www.dropbox.com/sh/szs0ifp7ds3km86/AADwesMpvg4Yx8t4FE_-8ewAa?dl=0

**Comment by pornel** [comment]
Indeed, I'm able to reproduce this.

`--floyd=0.5` usually helps avoid this bug.

**Comment by pornel** [comment]
Fixed in a8598d9cc62414c53543e94ac7f404a01e1bcce3
