### ISSUE TITLE
Version 2.4.2 outputs 2.4.1

### ISSUE THREAD

**Issue by toy** [pornel/pngquant#160]

**Comment by pornel** [comment]
Oh, I'll have to automate this :)

Anyway, it's not really wrong, because 2.4.2 binary is identical to 2.4.1, I've only updated copyright notices.

**Comment by toy** [comment]
I was wondering as diff showed only copyright changes.
And yes automating is a good idea ;)

**Comment by sergiomb2** [comment]
Hello Kornel Lesinski ,

Are you saying that we just have updates in lib ? 
I have one question. My question is:

     rpm -q --requires pngquant | grep quant

Should rpm force have same libimagequant version ?  

     libimagequant = 2.4.2-1.fc21
     libimagequant.so.0()(64bit)

or not , just : 

    libimagequant.so.0()(64bit)

What thoughts came up ?
Putting the question is an advance way, did lib change is ABI ?:D
Should we thought in versioning the lib ? For example have something like: 

    /usr/lib64/libimagequant.so.0 -> libimagequant.so.0.1.2
    /usr/lib64/libimagequant.so.0.1.2

**Comment by pornel** [comment]
There were no code changes between 2.4.1 and 2.4.2, so nothing needs to be updated.

The library has a stable ABI since 2.0.0, and I don't plan to break it (I may add new functions in the future).

**Comment by sergiomb2** [comment]
OK , so doesn't make sense tag it, for me ...
I thought you included what is in :
    
    git diff 2.4.2..master 

but seems that is reserved for 2.5.0 
-#define LIQ_VERSION 20401
-#define LIQ_VERSION_STRING "2.4.1"
+#define LIQ_VERSION 20500
+#define LIQ_VERSION_STRING "2.5.0"

Thanks for the info 

Best regards
