### ISSUE TITLE
What if pngquant was written in Rust?

### ISSUE THREAD

**Issue by pornel** [pornel/pngquant#161]
I'm seeking feedback on moving parts of pngquant from C99 to Rust. At first I'd only move pngquant CLI executable to Rust, but leave libimagequant as a pure C library.

It would build as a statically linked binary on OS X, Linux and Windows, x86 and x86_64. Rust's support for other architectures exists, but AFAIK is still immature.

How does this impact you?

**Comment by quiret** [comment]
I do not know. Just recently learned about Rust. I like the good performance of the libimagequant library, and as long as that stays, I guess it will be okay?

Make sure you do not change the API. Btw, still waiting on that custom palette setting function. :-)

**Comment by sergiomb2** [comment]
Hi, is Rust OS independent ? 
Rust does not exist in the Linux Fedora yet , still in review [1] 

[1] https://bugzilla.redhat.com/show_bug.cgi?id=915043

**Comment by pornel** [comment]
Rust certainly supports Linux, although it may take some time before distros create packages for it:
http://www.rust-lang.org/install.html

It also [getting musl support](https://github.com/rust-lang/rust/pull/24777), which AFAIR allows it to create static binaries that work without libc, so are compatible with any Linux distro (on x86/x64)

**Comment by rcanavan** [comment]
While support for Linux may just be a question of time, older and/or more exotic platforms such as IRIX will probably never get a functioning rust compiler. Currently, pngquant can be compiled basically everywhere even with ancient C compilers. I'd prefer if you'd stick with C and not use features from standards newer than C99.

**Comment by pornel** [comment]
Rust is [on its way to Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1356907) and [Debian](https://packages.debian.org/stretch/rustc). For platforms without packages it's easy to install and keep up to update via [rustup](https://www.rustup.rs). It can [target iOS, Android, *BSD, PPC and MIPS Linux](https://doc.rust-lang.org/nightly/book/getting-started.html#tier-2). Not IRIX though.

Currently pngquant is annoying on Windows due to poor C support in Visual Studio, POSIX-isms in the code, and need for bash-based configure script. OTOH Rust has very good support for Windows, and Cargo build scripts can be used to hide the pains of C integration.

For a while now I've stopped using C for and have been using Rust instead [for all new projects](https://imageoptim.com/api), and I'm quite happy with it. 

For now pngquant works well enough, so I don't feel pressure rewriting it immediately. But if I decide to add any major functionality, I'll probably split libimagequant and pngquant, and rewrite `pngquant.c` in Rust.

**Comment by sergiomb2** [comment]
Found this today: https://fedoramagazine.org/rust-meets-fedora/

**Comment by pickhardt** [comment]
I'd also recommend considering Go. It could be great for what you're trying to accomplish.

**Comment by pornel** [comment]
I see Go as a replacement for Java, and Rust as a replacement for C. Since pngquant and libimagequant are C projects, I would not use Go for them (especially that Go requires GC runtime that is problematic for libraries).

**Comment by ex** [comment]
Rust is fine, please not Go.

**Comment by pornel** [comment]
Now `cargo run` runs pngquant :)

It's still all 100% C, but everything is in Cargo packages. Almost builds on Windows, too.

https://crates.io/crates/imagequant-sys
https://github.com/pornel/pngquant/blob/master/Cargo.toml

**Comment by pornel** [comment]
[First Rust code](https://github.com/pornel/pngquant/blob/e131e331a2121019f7e7c795c7e999e895e68abd/rust/bin.rs#L27) has landed!

The good news is *the whole program **builds on Windows** out of the box*!

**Comment by pornel** [comment]
See #252
