### ISSUE TITLE
assertion in pam_colormap with colors == 0

### ISSUE THREAD

**Issue by quiret** [pornel/pngquant#163]
First off, thank you for your amazing work in libimagequant! Your recent addition, the possibility to add fixed colors, has really helped me with generating mipmaps for Grand Theft Auto 3, and I am sure that users of my future TXD editing tool will appreciate your work aswell.

Now to the issue. I am creating a liq_create_image_custom with dimension 1,1, add 256 palette colors to libimagequant fixed colors and quantize it. Sometimes the histogram has a size of zero (dont ask me why, I am just happy liq works!) and pam_colormap asserts...

assert(colors > 0 && colors < 65536) -- in pam.c, LIQ_PRIVATE colormap *pam_colormap...

I just added a check for "colors == 0" and then return a NULL. Turns out it doesnt break anything!

Do you approve of this? :) The issue is in the msvc branch, not sure if fixed elsewhere.

On a sidenote, I would love if a function called "liq_set_allow_palette_sorting( liq_attr*, int )" made it into libimagequant, so that the output indice correspond to the palette I gave libimagequant through lig_image_add_fixed_color. Turns out that just disabling "sort_palette" call in pngquant_quantize does the trick!

**Comment by pornel** [comment]
So you're using the library to remap files to an existing, known palette, rather than to generate a new palette? That's a use-case I haven't thought about.

In that case 0 colors in the new palette, or histogram after removal of fixed colors, could happen. I'll see if code can work with that safely.

**Comment by quiret** [comment]
Yes! I also liq_set_max_colors to the amount I gave as "fixed colors", so I kinda tell liq to not modify the palette. The color search algorithm is pretty sweet I gotta say!

**Comment by pornel** [comment]
Ok, fixed in 1a744c63a98ce1d611a187d5d32fa800ca73a7eb
