### ISSUE TITLE
Make it possible to disable gamma correction

### ISSUE THREAD

**Issue by ryanackley** [pornel/pngquant#164]
I am working on OS X and was wanting to use pngquant to compress screenshots. When I use pngquant, the colors subtly change from my source image. The colors become a little more saturated. I'm assuming this is caused by the gamma correction because the palette is so limited. It would be nice if I get to decide what gamma setting I want.

For my purposes, I want the result to look exactly like the original image (or as close as possible).

**Comment by pornel** [comment]
Gamma correction and color profiles are features of the PNG format, so strictly speaking they can't be disabled, they can just be handled one way or another (e.g. ignored and discarded, or applied).

**Comment by ryanackley** [comment]
The screenshot is taken on OS X but pngquant is compiled and running on a linux server. It's compiled against libpng 1.6.18. 

My image processing pipeline is this:

1. Take a screenshot on Mac
2. Add annotations using html.
3. Send to server and rasterize to png with phantomjs
3. Compress png with pngquant. 
4. Return to client

If I leave out step 4, the screenshot colors in the final image look **exactly** like the original. 

It seems likely that the resulting image's gamma is different than the original's because the image is always slightly darker than the original when compressed with pngquant. From what I can tell the pngquant source code _always_ sets the output gamma to 2.2, even if you have it set to something different in the source PNG file. Shouldn't that be a user setting? or shouldn't respect the gamma setting on the input?.What do you think?

**Comment by pornel** [comment]
On Linux you *must* compile with libcms2 if you want OS X's color profile to be respected. Otherwise Linux version doesn't know what to do with the color profile and discards it.

**Comment by pornel** [comment]
In 2.6 I've improved handling of files without color profiles, but I think in this case the problem is caused by lack of color profile handling in the linux build.
