### ISSUE TITLE
replace_file function has a bug in it.

### ISSUE THREAD

**Issue by henrygg** [pornel/pngquant#165]
when "unlink" is called, the error code is not checked and can cause the following "rename" function call to fail. It is better to check and put a couple of times of trying here .

**Comment by pornel** [comment]
Checking unlink would be pointless:

* if unlink succeeds and rename succeeds, that's a success.
* if unlink fails and rename fails, that's a failure.
* if unlink fails, but rename succeeds, that's a success (this will when the destination file doesn't exist).
* if unlink succeeds, but rename fails, that's a failure.

As you can see, logically result of unlink is not supposed to have influence on result of this function.

**Comment by henrygg** [comment]
Here is a scenario, a thread creates a process to exec pngquant to compress a file and the thread waits for the file to be finished. To pngquant, if the output file and the input file has the same file name(kind of in-place compressing), it is possible the "to" file is still accessed when "unlink" is called against it. (The case occurs in the real scenario), it may be fully released after hundreds of microseconds

**Comment by pornel** [comment]
Oh, I shouldn't allow source and destination to be the same in this case.

**Comment by pornel** [comment]
No, wait, it isn't, because it's written to a temp file first.

**Comment by henrygg** [comment]
Specify input file name A and output file name A
the following occurs.
1. Read A and Compress to B
2. Unlink A
3. Rename B to A
if "Unlink A" is called at step 2  while A is still kind of accessed internally by Windows, it fails
If try a couple of times of continuously calling Unlink every 200 ms, "A" might be fully released and "Unlink A" will succeed.

**Comment by pornel** [comment]
Is Windows _really_ that broken? `read_image` calls `fclose`, so this function shouldn't return until it closes the file.

**Comment by quiret** [comment]
What an obscure scenario. What would this internal access by Windows be, anyway?
