### ISSUE TITLE
liq_get_quantization_quality - Incorrect values when used after remapping?

### ISSUE THREAD

**Issue by swillits** [pornel/pngquant#168]
Related to #167 , I don't think it actually works hows it's documented, either. If I quantize an image and then remap several images with that same quantization, the quality returned is always that of the very first image. 

I haven't dug around the internals much, but this is what I've noted. In liq_write_remapped_image_rows the "remapping_error" var has the right value I want. This condition at the end of the function prevents it from being assigned to result->palette_error:

```
if (result->palette_error < 0) {
        result->palette_error = remapping_error;
    }
```

And even if it was, then in lib_get_quantization_quality, it seems like the first condtion will always be true, so it'll never return result->remapping->palette_error anyway:

```
 if (result->palette_error >= 0) {
        return mse_to_quality(result->palette_error);
    }
```

So what I ended up doing was modifying the code so that the remapping_error var in liq_write_remapped_image_rows is accessible to me, and it appears that it does indeed have exactly the values I want, and made the code work as I expected.

So I'm not sure where the problem is in the existing code, but something somewhere doesn't seems to be right.

**Comment by pornel** [comment]
OK, that function had confusing identity. I've added `liq_remapping_quality` for reporting actual remapping results, rather than that quirky thing the library uses internally for estimating quality :)

**Comment by swillits** [comment]
Cool. That's what my solution was too. :-)

Thanks.
