### ISSUE TITLE
Quality changes in pngquant versions

### ISSUE THREAD

**Issue by tkoenig** [pornel/pngquant#172]
Hi, 
we noticed some  quality regression when upgrading pngquant to the latest version, especially when working with gradients:

Source:
![2048-without-pngquant](https://cloud.githubusercontent.com/assets/63860/9988013/551c2b7e-604d-11e5-960c-7fb122a42aa5.png)

Old pngquant: 
```
pngquant, 2.0.1 (September 2013), by Greg Roelofs, Kornel Lesinski.
   Compiled with SSE2 instructions.
   Compiled with libpng 1.2.42; using libpng 1.2.42.
```

![2048-with-pngquant-old](https://cloud.githubusercontent.com/assets/63860/9988042/7aaf790e-604d-11e5-8e43-dd8680fdbfa0.png)

New pngquant:

```
pngquant, 2.5.2 (September 2015), by Greg Roelofs, Kornel Lesinski.
   Compiled with SSE instructions.
   Color profiles are supported via Little CMS. Using libpng 1.6.18.
```

![2048-with-pngquant-new](https://cloud.githubusercontent.com/assets/63860/9988066/b1d9c4b6-604d-11e5-9a73-e88f1301b49b.png)

The options used to generate the PNG's are the same between old and new:

`pngquant 2048.png --quality=80-100 --ext .png --force`

If you compare the images you'll notice quite a difference in the gradients, whereas the new pngquant looks darker. Additionally the file size increased in the new version of pngquant in this comparison.

Did there anything substantial change between these versions? Is there anyway to achieve the same quality with the new version?

**Comment by pornel** [comment]
The new version supports color profiles, while the old one was ignoring them and having wrong colors.

The new version has more accurate color search and dithering algorithm that doesn't erroneously render flat areas and color streaks.

**Comment by tkoenig** [comment]
Thanks for clarification. 

Still if you compare the images i have supplied the old version of pngquant comes closer to the original than the new one.

So what you are saying is the quality should be generally improved when switching to the new version, but not in all cases – is this assumption correct?

**Comment by pornel** [comment]
Yes. 

Keep in mind that your file has a cHRM chunk that affects color brightness and saturation. 

The image from pngquant without color profile support will be closer to how the image is displayed in other programs that don't do proper color management.

The image from pngquant with color profile support will be closer to how the image is displayed (and is supposed to be displayed) in other programs that do proper color management.
