### ISSUE TITLE
Windows binary 2.5.2 using old libpng

### ISSUE THREAD

**Issue by hachigoro** [pornel/pngquant#173]
Hi,

I downloaded the current Windows binary, but when I run it it says the version of pngquant is 2.5.2, but the version of libpng is 1.2.52.

This makes a warning message show up saying libpng is too old. The previous Windows binaries were compiled using a more recent libpng. Would it be possible to make a Windows binary using a newer libpng?

Thanks!

**Comment by pornel** [comment]
#171

**Comment by pornel** [comment]
@cssignet might know

**Comment by cssignet** [comment]
pngquant, 2.5.2 (October 2015) - 3/10/15
zlib 1.2.8 and libpng 1.6.18
http://css-ig.net/tools/public/pngquant.zip

**Comment by pornel** [comment]
Thank you @cssignet!

**Comment by petrdiblik** [comment]
Hi,
Is that OK that version 2.5.2 with libpng 1.2.52 gives slightly different results than version 2.5.2 (the same) with libpng 1.6.18?

**Comment by pornel** [comment]
@petrdiblik yes, that's expected.

**Comment by hachigoro** [comment]
Thanks for making that build. However when I run it, I get this message: "Compiled without support for color profiles."

I didn't see that message in previous versions, is that something to be concerned about?

Thanks.

**Comment by pornel** [comment]
In previous version it'd say "compiled *with* support for color profiles" and be quiet otherwise. So nothing changed in actual capabilities.
