### ISSUE TITLE
How to use --with-libpng

### ISSUE THREAD

**Issue by cmyk** [pornel/pngquant#174]
I tried to compile pngqant on debian 8. I have installed pnglib 1.6.18.
But it's using the packaged version.

```
#:~/src/pngquant-2.5.0$ which libpng-config
/usr/bin/libpng-config
#:~/src/pngquant-2.5.0$ libpng-config --version
1.6.18

#:~/src/pngquant-2.5.0$ ./configure

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.2.50)
      zlib: shared (1.2.8)
     lcms2: shared (2.6)
```

**Comment by pornel** [comment]
I didn't know libpng-config existed. The configure script uses pkg-config.

**Comment by cmyk** [comment]
Well, I don't know how to compile pngquant with 1.6.18.

**Comment by pornel** [comment]
If you put libpng 1.6 in the same directory and compile it, then pngquant's configure will find it and link statically

**Comment by pornel** [comment]
or

```sh
./configure --with-libpng=$(libpng-config --prefix)
```

**Comment by sergiomb2** [comment]
Hi, cmyk you need install libpng-dev because  -dev package got the pkgconfigs 

Reference: 
https://packages.debian.org/experimental/amd64/libpng16-dev/filelist

**Comment by cmyk** [comment]
@pornel, that didn't work. Tried that already.

@sergiomb2 thanks for that but I tried to mess with experimental once, and it shot the whole system.
It wants to remove dependencies...
```
osm@map:~/src/pngquant-2.5.0$ sudo apt-get -t experimental install libpng16-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libcairo-gobject2 libcairo-script-interpreter2 libcurl4-gnutls-dev libdap-dev libgcrypt20-dev libgif-dev libgmp-dev libgmpxx4ldbl libgnutls28-dev libgnutlsxx28 libidn11-dev libjasper-dev libkrb5-dev liblzo2-2 libmysqlclient-dev
  librtmp-dev libspatialite-dev libssh2-1-dev libtasn1-6-dev libtasn1-doc libxerces-c-dev libxext-dev nettle-dev unixodbc-dev x11proto-xext-dev
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libpng16-16 libpng16-tools
The following packages will be REMOVED:
  libcairo2-dev libfontconfig1-dev libfreetype6-dev libgdal-dev libgdal1-dev libpng12-dev
The following NEW packages will be installed:
  libpng16-16 libpng16-dev libpng16-tools
0 upgraded, 3 newly installed, 6 to remove and 125 not upgraded.
Need to get 736 kB of archives.
After this operation, 36.1 MB disk space will be freed.
Do you want to continue? [Y/n] n
```

**Comment by pornel** [comment]
Ugghhh. Debian has a serious problem with being stuck with a 10-year-old version of libpng, and they can't upgrade it because some old packages don't support anything newer :(

So on Debian specifically you have to compile your own copy of libpng from source (not a package), and then specify that directory in pngquant's configure:

```
./configure --with-libpng=/tmp/my/libpng1.6/
```

It'll link statically to it if it finds `libpng*.a` in there.

**Comment by sergiomb2** [comment]
@pornel LOL 
@cmyk 
The following packages will be REMOVED:
  libcairo2-dev libfontconfig1-dev libfreetype6-dev libgdal-dev libgdal1-dev libpng12-dev

Doesn't look so bad , but I can't help you much.

Looking in my Fedora system we got : 
libpng10 1.0.61
libpng12 1.2.50
libpng15 1.5.18
libpng 1.6.10 

by https://tracker.debian.org/pkg/libpng  and https://tracker.debian.org/pkg/libpng1.6
looks like Debian just have libpng 1.2 , so yes I think @pornel advice is wise, (use a local copy of libpng )

**Comment by cmyk** [comment]
@pornel Thanks, for your time. I had compiled libpng 1.6.8.
And there's the libs here 

``` #:~/src/libpng-1.6.18/.libs$ ls -alh
total 5.1M
-rw-r--r-- 1 ### ### 1.4M Oct  1 12:02 libpng16.a
```

Still the same result:

```#:~/src/pngquant-2.5.0$ ./configure --with-libpng=~/src/libpng-1.6.18/.libs/

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.2.50)
      zlib: shared (1.2.8)
     lcms2: shared (2.6)
```

**Comment by pornel** [comment]
Try

    ./configure --with-libpng=/home/###/src/libpng-1.6.18/

**Comment by cmyk** [comment]
Weird... that workd!

``` 
#:~/src/pngquant-2.5.0$ ./configure --with-libpng=/home/###/src/libpng-1.6.18/

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: static (1.6.18)
      zlib: shared (1.2.8)
     lcms2: shared (2.6)

```

**Comment by rkravchik** [comment]
@pornel could you help with static compiling?
I've tried:
- to put "libpng.a" in pngquant src directory and then ./configure
- to put "libpng.a" in pngquant src/lib directory and then ./configure
- exec ./configure --with-libpng=/home/###/libpngsrc   (there is compiled "libpng.a")
but always get
 Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: error ... not found (try: `apt-get install libpng16-dev` or `apt-get install libpng-dev` or `yum install libpng-devel`)

When i've installed libpng with make install, then ./configure finds its shared version:
  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.6.29beta03)
      zlib: shared (1.2.7)
     lcms2: no

How to statically compile pngquant with libpng on CentOS 7?
