### ISSUE TITLE
Optimizating with a range of qualities. Bug?

### ISSUE THREAD

**Issue by RGGN** [pornel/pngquant#177]
Hey!

It's my first time posting here, congratz for pngquant, it's a great tool!

The thing is that i'm compressing this image: http://imgur.com/MtNxv6d
With this command:  'pngquant -v --quality=60-90 test.png'

And the process never finish! It gets stuck in 'moving colormap towards local minimum'. By the way, if I run the command without the 'quality' option it works fine. But i had to post this because it happened with a single image out of 20k, i dont know what does this image so special.

Thanks, and good work!

**Comment by petrdiblik** [comment]
Works for me.
(The image is not saved with these quality settings because 256 colors result in quality 38. But the process finishes correctly.)
pngquant 2.5.2, libpng 1.6.18

**Comment by pornel** [comment]
Can you send me (or attach here)  the image that is causing this bug? 

Which version of pngquant are you using?

**Comment by RGGN** [comment]
Ok! My fault! I'm using pngquant 2.0.1, libpng 1.2.50. I guess it's solved in the newest release. Sorry for the inconvenience!

**Comment by pornel** [comment]
OK, that one has been fixed indeed.
