### ISSUE TITLE
skip-if-larger skips images which are actually smaller

### ISSUE THREAD

**Issue by s-diez** [pornel/pngquant#182]
I just encountered a problem with skip-if-larger in Version 2.5.2 (October 2015) on Linux.
The original image is 132KB. If I set the option skip-if-larger it refuses to write the image as it thinks it is to big.
~~~
read 132KB file
  made histogram...36776 colors found
  selecting colors...4%
  selecting colors...7%
  selecting colors...11%
  selecting colors...32%
  selecting colors...52%
  selecting colors...56%
  selecting colors...76%
  selecting colors...97%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...18 entries transparent
  mapped image to new colors...MSE=17.667 (Q=49)
  writing 256-color image as peerfectglide.png
  file exceeded expected size of 31KB
Skipped 1 file out of a total of 1 file.
~~~

If I execute the same command without skip-if-larger the image size is reduced to 40KB.

~~~
read 132KB file
  made histogram...36776 colors found
  selecting colors...4%
  selecting colors...7%
  selecting colors...11%
  selecting colors...32%
  selecting colors...52%
  selecting colors...56%
  selecting colors...76%
  selecting colors...97%
  selecting colors...100%
  moving colormap towards local minimum
  eliminated opaque tRNS-chunk entries...18 entries transparent
  mapped image to new colors...MSE=17.667 (Q=49)
  writing 256-color image as peerfectglide.png
No errors detected while quantizing 1 image.
~~~

Command used is the following (with and without skip-is-larger):

~~~
/opt/pngquant/bin/pngquant -v -f 'PATH_TO_IMAGE/peerfectglide.png' -o 'PATH_TO_IMAGE/peerfectglide.png'
~~~

**Comment by pornel** [comment]
So this option is actually `--skip-if-larger-or-if-quality-dropped-so-much-that-it-may-not-be-worth-filesize-saving`, but I had to use a shorter name ;)

There's an additional check in pngquant that compares quality loss to filesize reduction, and tries to skip files if drop in quality was bigger than drop in file size.

Your case is interesting, because it has both big quality drop, and big filesize drop.

Could you share that image?

**Comment by pornel** [comment]
Thanks for the image. I've tuned logic to allow that conversion d5ab47988bb437a4f2bfdd2ee48b532614896115
