### ISSUE TITLE
pngquant not working on my CENTOS 6.7 x86_64 virtuozzo – nex

### ISSUE THREAD

**Issue by mianahmad** [pornel/pngquant#185]
i know it's kind of a childish question, i am not coming straight to you for this solution.
i searched all over the internet  but i did not found the solution for installing this extension.
My server is running on unix (**CENTOS 6.7 x86_64 virtuozzo**)
i am using this code:
`exec('wget https://github.com/pornel/pngquant/tarball/master');`
`exec('tar xzf master');`
so a directory name **pornel-pngquant-34ba88e** was created so i selected that directory.
`cd pornel-pngquant-34ba88e`
`exec('./configure');`
`exec('make');`
`exec('sudo make install');`
**i also tried this:**
`  exec(' su root);`
` exec(' make install');`
Not only this i also tried this 
`exec('yum install make gcc libpng-devel && make');`

i tried almost every possible solution for installing pngquant on my server but failed.
i am getting this error:

`
 Fatal error: Uncaught exception 'Exception' with message 'Conversion to compressed PNG failed. Is pngquant 1.8+ installed on the server?' in /home/next/public_html/in.php:39 Stack trace: #0 /home/next/public_html/in.php(47): compress_png('help2kl.png') #1 {main} thrown in /home/next/public_html/in.php on line 39
`

i know i am not even 1% of your knowledge but can you please write me some command step by step so that i can inst

**Comment by pornel** [comment]
That `exec()` looks odd. Are you trying to install it from inside another application?

Did you get any errors when you ran `make` or `make install`? Does running `pngquant` from command line work?

**Comment by sergiomb2** [comment]
hey , you got pngquant-2.5.2-5.el6 on epel6 stable repos , you may try it please

**Comment by mianahmad** [comment]
Thanks @pornel  for replying..
i am running those commands from php files.. shell access is enabled on my server..
@sergiomb2 i also tried latest version...
then i also run this command 
`exec('pngquant --version');`
but nothing happen..

i know your time is much more valuable according to me. but your few minutes can save my hours..

**Comment by mianahmad** [comment]
Well every thing is setup now...
also `pngquant `command is working...
i run this command..
`pngquant --version`
**result** : 2.5.2 (October 2015)

so it means extension is installed but its not working in my php file...

**Comment by mianahmad** [comment]
Thanks @pornel  for your valuable time..
at last issue is solved... 
i used this command to compress image:
`echo $get_compress = exec("find /image/source/path -name '*.png' -exec /usr/local/bin/pngquant -ext .png -force 256 {} \;");`

**Comment by sergiomb2** [comment]
Cool, we may close this bug :)
