### ISSUE TITLE
Convert configure(s) from bash to posix shell

### ISSUE THREAD

**Issue by aklv** [pornel/pngquant#186]
Convert configure(s) from bash to posix shell. Should work in any shell which calls itself posix compliant sh and continues to work in bash.

Most changes are trivial like replacing '=~' with grep -q, '&>' with 2>&1 '<()' with echo '...' | cc -  and [[..]] with [..].
The array replacement code is a little tricky, mostly because it destroys positional parameters. It should not matter at this point, but if it is, this can be easily fixed by wrapping code in the function.

[patch-configure.txt](https://github.com/pornel/pngquant/files/128906/patch-configure.txt)
[patch-lib_configure.txt](https://github.com/pornel/pngquant/files/128907/patch-lib_configure.txt)

**Comment by pornel** [comment]
What platforms don't have bash?

**Comment by aklv** [comment]
BSD*, e.g. FreeBSD, Dragonfly, etc.

**Comment by pornel** [comment]
Thank you for the patches. However, I've decided not to apply them.

The systems I usually test on don't have the real `sh`, so sooner or later I'd accidentally sneak some bash-isms back. The number of gotchas in the bash language scares me, so workarounds for sh on top of that worry me even more.

Also, the project already relies on GNU-isms in its Makefiles, so BSD systems will need to deal with the GNU/Linux bias of the project anyway ;)
