### ISSUE TITLE
remove libpng sRGB profile check?

### ISSUE THREAD

**Issue by pdknsk** [pornel/pngquant#190]
From a more recent libpng manual.

> Error detection in some chunks has improved; in particular the iCCP chunk
> reader now does pretty complete validation of the basic format.  Some bad
> profiles that were previously accepted are now accepted with a warning or
> rejected, depending upon the png_set_benign_errors() setting, in particular
> the very old broken Microsoft/HP 3144-byte sRGB profile.  Starting with
> libpng-1.6.11, recognizing and checking sRGB profiles can be avoided by
> means of
> 
>     #if defined(PNG_SKIP_sRGB_CHECK_PROFILE) && \
>         defined(PNG_SET_OPTION_SUPPORTED)
>        png_set_option(png_ptr, PNG_SKIP_sRGB_CHECK_PROFILE,
>            PNG_OPTION_ON);
>     #endif

The mentioned *broken* sRGB profile is commonly used, not broken, and is the standard sRGB profile written by Photoshop. This bogus check just adds a confusing warning when ```verbose``` is set.

```
  iCCP: known incorrect sRGB profile
```

**Comment by pornel** [comment]
I think that's a problem of libpng. If the profile is not broken, libpng should fix their detection.

I've added libpng warning prefix to make it clearer it's just a warning, and that libpng is to blame :)

730f9061589f8e3bb428b9ccd72497e464074576

**Comment by pdknsk** [comment]
> If the profile is not broken, libpng should fix their detection.

It won't happen. [The author doesn't care.](https://sourceforge.net/p/png-mng/mailman/message/32003609/)

**Comment by pdknsk** [comment]
To clarify the impact of this change: this is the only profile libpng checks for and reports on.

**Comment by pornel** [comment]
I see. In that case removing the check makes sense indeed.
