### ISSUE TITLE
pngquant - 2.7.0 (April 2016) - windows binary

### ISSUE THREAD

**Issue by cssignet** [pornel/pngquant#191]
pngquant - 2.7.0 (April 2015) - 16/04/2016
zlib 1.2.8 and libpng 1.6.21
http://css-ig.net/tools/public/pngquant.zip

**Comment by pornel** [comment]
Thank you

**Comment by cssignet** [comment]
i had to re-compile, so this is with [d5ab479](url=https://github.com/pornel/pngquant/commit/d5ab47988bb437a4f2bfdd2ee48b532614896115)
http://css-ig.net/tools/public/pngquant.zip
