### ISSUE TITLE
better palette sorting

### ISSUE THREAD

**Issue by pdknsk** [pornel/pngquant#193]
The palette is sorted by popularity, which produces good results, but probably not the best. A while back I read [this interesting page](http://css-ig.net/articles/outil-couleurs-palette) (in French, but Google Translate works well enough), which compares different palette sorting methods.

I've implemented two methods mentioned on the page in branch [palette](https://github.com/pornel/pngquant/commit/c0ec99e3191e9a6bd000b18c290dace37fe0decc).

1. Pick the first color based on *popularity*, and then pick the color with the least distance next.
2. Like 1. but picks the first color based on *luminance*.

The first approach usually gives 2-3% improvement, and is rarely worse than the currrent method.
The second is sometimes much better than the first, but is sometimes worse than the current method.

Some example numbers. (I used more PNGs when testing this.)

Current | Popularity | Luminance
-----------|---------------|---------------
121703 | 121108 | 115053
16284 | 16049 | 16586
7727 | 7665 | 7746
32944 | 32156 | 32162
80186 | 79732 | 75214

This needs further testing with more PNGs. And I've not tested extensively if sorting transparent and non-transparent colors still gives better results in these cases. It appears so.

To switch between *popularity* and *luminance* alternate between these two lines in the source.
```c
    qsort(map->palette + start, nelem, sizeof(map->palette[0]), compare_popularity);
    // qsort(map->palette + start, nelem, sizeof(map->palette[0]), compare_luminance);
```
Another [interesting link](http://www.alanzucconi.com/2015/09/30/colour-sorting/), which mentions *Hilbert sorting*, and *Travelling Salesman sorting*. It's not specific to palettes, so there are no results, but it might be worth trying. (I can't do it.)

It could also be an option to have many different methods, and then compare the size at a lower zlib compression level, which is faster and usually still gives a good approximation of compressibility.

**Comment by pornel** [comment]
Where does the improved compression come from? Is it because of increased applicability of the sub filter? If so, it may be possible to optimize for that explicitly.

Have you tried sorting by popularity first, then splitting it in 2-3 bands, and sorting each by band hue/luminance individually? I'm assuming that savings come from sub filter, so it produces low numbers. A mix of popular (low-numbered) colors and low numbers where similarity works could give nice results.

**Comment by pdknsk** [comment]
The numbers are with the current filter, which is ```NONE```. The better compression is because for some reason the colors arranged in different ways suit ```deflate``` better.

**Comment by pornel** [comment]
That is surprising. AFAIK deflate doesn't care about values, only about their frequency and repetition.

Are images identical? Maybe remapping step chooses colors differently?

**Comment by pdknsk** [comment]
Hmmm, you're right. The images are different. It was too good to be true. I checked that the images turn out identical early on, but introduced a [small bug](https://github.com/pornel/pngquant/commit/bcb7f2940b6c3f938d0498b30db6af97b3b877e7) later. with the bug fixed images are identical, but a few bytes larger.

I'll close the bug. The palette can be improved, but only with advanced filter heuristics, which should better be left to dedicated applications IMO.
