### ISSUE TITLE
Custom palettes

### ISSUE THREAD

**Issue by rr-** [pornel/pngquant#194]
The main strength of pngquant comes from its capability of coming up with great palettes on its own. It would be useful, however, to let the user pass custom palette (in an ideal world, with >= 256 colors) so that we could use pngquant as a ditherer too.

I know of `--map` option, but it still comes up with new colors?

**Comment by pornel** [comment]
`--map` has a quirk that it ignores palette entries that aren't used in the given image, but apart from that it _should_ use the colors exactly.

If map file has fewer than 256 colors, then specify that number of colors. Otherwise pngquant will use extra ones.

On libimagequant level you can specify fixed palette colors.

**Comment by rr-** [comment]
>If map file has fewer than 256 colors, then specify that number of colors. Otherwise pngquant will use extra ones.

I missed that, thanks. However, it still works funny:

![pal](https://cloud.githubusercontent.com/assets/1045476/15065911/b3a3d6e0-1364-11e6-876a-d7ce0640365b.png)

+

![test](https://cloud.githubusercontent.com/assets/1045476/15065916/bca1deb8-1364-11e6-99a2-340c7294ebb8.png)

+

```console
pngquant -f --map pal.png 4 -- test.png
```

 =
![test-fs8](https://cloud.githubusercontent.com/assets/1045476/15065920/c1b3ac60-1364-11e6-9d9c-81868d67b5cf.png)

Not sure where the orange was taken from?

**Comment by pornel** [comment]
That was palette postprocessing that guarantees local optimum for that palette. I've disabled it for the map option: b3e06e6182d725288493783bdcf74210059a83ec

**Comment by rr-** [comment]
Brilliant! Thanks.

**Comment by pornel** [comment]
BTW: libimagequant API has support for custom palette via https://pngquant.org/lib/#liq_image_add_fixed_color
