### ISSUE TITLE
does not dither on parts of difficult image

### ISSUE THREAD

**Issue by pdknsk** [pornel/pngquant#195]
Let me preface by writing this is probably not an image you'd typically use with ```pngquant```. It still does fantastically well, with two exceptions. On Yoshi and Luigi, it introduces very noticeable banding.

![am](https://cloud.githubusercontent.com/assets/1097609/15052998/b18efa60-1300-11e6-83e6-42575e04acb6.png)

![am256](https://cloud.githubusercontent.com/assets/1097609/15052997/b18c83ca-1300-11e6-9893-a4ae4ecac5a8.png)

Even with the few green colors picked for the palette, dithering would probably produce better results. If not, just adding a few additional colors for those parts might not hurt the rest of the image noticeably, I think.

**Comment by pornel** [comment]
I've tuned dithering to support this case a bit better:

![b18efa60-1300-11e6-83e6-42575e04acb6-fs8](https://cloud.githubusercontent.com/assets/72159/15073270/982d4d8e-1390-11e6-823c-4037d6cbd9a9.png)
