### ISSUE TITLE
Supporting per-channel posterization

### ISSUE THREAD

**Issue by jamesbowman** [pornel/pngquant#196]
It would be useful for some devices to support per-channel posterization values. So (for example) RGB565 could be supported by `--posterize 3/2/3`, and ARGB15555 by `--posterize 7/3/3/3`.

Looking at the source it seems possible. Would it be OK if I sent you a pull request for this?

Thanks!

**Comment by pornel** [comment]
Yes, please!

**Comment by pornel** [comment]
Are you still interested in this?

**Comment by jamesbowman** [comment]
Thanks for the reminder. Closing.
