### ISSUE TITLE
Full-transparency handling

### ISSUE THREAD

**Issue by joliss** [pornel/pngquant#199]
When quantizing the following image, pngquant turns fully-transparent pixels into almost-transparent pixels.

![cards.png](https://cloud.githubusercontent.com/assets/524783/15516434/c294bb58-21ea-11e6-8f3e-56ec237af81c.png)

The first pixel row starts with a gradient from fully-transparent black to fully-opaque black:

![cards png 4ipvm](https://cloud.githubusercontent.com/assets/524783/15516790/660a0418-21ec-11e6-969d-a87475292a08.png)

```
$ convert cards.png txt:- | head -n 7 | grep -o '#[0-9A-F]\+'
#00000000
#00000000
#0000001D
#00000095
#000000E7
#000000
```

If I were to manually quantize the image, I'd definitely assign a palette entry to full transparency, in part because there's enough transparent pixels to justify this, and in part because full transparency is a particularly important color value.

However, pngquant chooses an almost-transparent pixel value instead:

```
$ pngquant -s 1 64 < cards.png | convert png:- txt:- | head -n 7 | grep -o '#[0-9A-F]\+'
#00000012 <--- top-left pixel becomes almost-transparent; #00000000 would be better
#00000012
#00000012
#00000083
#000000E9
#000000
```

This leads to a rectangular "shadow" around the image when I use it on a page:

![untitled 2 639w3](https://cloud.githubusercontent.com/assets/524783/15517321/118224fe-21ef-11e6-88c2-f7048097219a.png)

I initially thought that this was an averaging effect, where pngquant moves away from the edges of the color space to reduce mean error. If this is the case, I'd like to suggest special-casing full transparency (perhaps weighing errors on full transparency higher), because full transparency seems like a particularly important color for many applications.

However, curiously, if we flatten the image and turn transparency into an opaque color that isn't used elsewhere in the image (here: #00ff00), then pngquant matches the precise color value:

```
$ convert cards.png -background '#00ff00' -flatten png:- | pngquant -s 1 64 \
      | convert png:- txt:- | head -n 7 | grep -o '#[0-9A-F]\+'
#00FF00 <--- precise color value
#00FF00
#00E600
#007C00
#001B00
#000000
```

I went spelunking in the code to see if alpha sensitivity is to blame, and found commit 89929a806743f6e12fac25ed2c6433f1fe112284. This change seems a bit dubious to me: If we use average instead of max, we weigh the difference between rgb(0, 0, 0) and rgb(1, 1, 1) twice as high as the difference between rgba(0, 0, 0, 0) and rgba(0, 0, 0, 1). If I try and revert this commit (I sent you a patch at #198, just so you can try it for yourself), I get a slight improvement, from `#00000012` to `#0000000A`, but still no full transparency:

```
$ pngquant -s 1 64 < cards.png | convert png:- txt:- | head -n 7 | grep -o '#[0-9A-F]\+'
#0000000A
#0000000A
#0000000A
#00000083
#000000E5
#000000
```

So now I'm still not sure about the root cause of this problem, or what best to do to improve it.

**Comment by pornel** [comment]
That's a great find. I've changed from max to avg, because it's typical performance was slightly better than max, but I didn't know about such counter-example.

**Comment by pornel** [comment]
I've fudged it a little in fb571dfc74d37598414d27a7105acce1c4f43795

I'm afraid the root cause is the limitation of median cut.

**Comment by joliss** [comment]
Thank you, works great!
