### ISSUE TITLE
Error cannot decode image

### ISSUE THREAD

**Issue by evilebottnawi** [pornel/pngquant#200]
```shell
error: Read error (libpng failed)\n  error: cannot decode image 3fba6a18-fe5a-4fd6-872d-05262a0e8cab\n
```
![8ead41a2de2df5a1d92a118e55a25746-300x211](https://cloud.githubusercontent.com/assets/4567934/15574434/fa478474-2355-11e6-85b4-a7818398698b.png)

**Comment by pornel** [comment]
Are you using libpng older than 1.6?

**Comment by evilebottnawi** [comment]
@pornel thanks, In the near future I will try to explore in more detail what is wrong is happening

**Comment by patricmutwiri** [comment]
We're in 2017 and I'm getting the error!

**Comment by pornel** [comment]
Please run:

    pngquant -h

and report what version of pngquant and libpng you have.

**Comment by patricmutwiri** [comment]
pngquant, 2.5.0 (June 2015), by Greg Roelofs, Kornel Lesinski.
Using libpng 1.2.54.

**Comment by pornel** [comment]
Yeah, so the problem is in buggy libpng 1.2 installed in the system, same as https://github.com/pornel/pngquant/issues/200#issuecomment-221904805

You need to install pngquant from a less-horribly-outdated Linux distribution.

**Comment by patricmutwiri** [comment]
Horrribly outdated?  Like which one now?

**Comment by pornel** [comment]
You need libpng 1.4 at minimum. You have libpng 1.2 which is old and buggy.

**Comment by Lorenza** [comment]
Hi.
I'm using pngquant on a mac, I've installed it through brew.
pngquant, 2.12.5 (July 2019) (Rust), by Kornel Lesinski, Greg Roelofs.
libpng 1.6.37

And I'm experiencing the error.
error: Read error (libpng failed)
error: cannot decode image
Shall I have to move back to a different libpng version?
Thanks

**Comment by kornelski** [comment]
1.6.37 is fine. If new libpng version shows an error, it's probably right — the image is damaged/invalid, or it's not a PNG.

**Comment by Lorenza** [comment]
I can see with identify (ImageMagick) something like that

04d9000f-abf1-433e-a348-7d8c67c0ebfb_0.png PNG 1024x2402 1024x2402+0+0 8-bit sRGB 918926B 0.000u 0:00.000

![image](https://user-images.githubusercontent.com/5046879/66734279-bb69f580-ee62-11e9-8ae6-0997ade59261.png)

is it invalid somehow?
Thanks

**Comment by zvezdochiot** [comment]
Use https://pmt.sourceforge.io/pngcrush/

**Comment by kornelski** [comment]
The image you've attached decodes fine for me (I have libpng 1.6.26)
