### ISSUE TITLE
Error creating package with checkinstall

### ISSUE THREAD

**Issue by ingria** [pornel/pngquant#204]
Possibly related issue: #149
OS: Ubuntu 16.04 x64

Builds succesfully:

``` bash
~/pngquant# make
  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.6.20)
      zlib: shared (1.2.8)
     lcms2: no
```

Trying to `checkinstall`:

``` bash
~/pngquant# checkinstall
...blah blah...
*****************************************
**** Debian package creation selected ***
*****************************************

This package will be built according to these values: 

0 -  Maintainer: [ user@machine ]
1 -  Summary: [ PNG quantization tool for reducing image file size ]
2 -  Name:    [ pngquant ]
3 -  Version: [ 2.7.2 ]
4 -  Release: [ 1%{?dist} ]
5 -  License: [ GPL ]
6 -  Group:   [ checkinstall ]
7 -  Architecture: [ amd64 ]
8 -  Source location: [ pngquant ]
9 -  Alternate source location: [  ]
10 - Requires: [ libpng%{?_isa} >= 1.2.46-1
zlib%{?isa} >= 1.2.3-1 ]
11 - Provides: [ pngquant ]
12 - Conflicts: [  ]
13 - Replaces: [  ]

======================== Installation successful ==========================
Copying files to the temporary directory...OK
Stripping ELF binaries and libraries...OK
Compressing man pages...OK
Building file list...OK
Building Debian package... FAILED!
*** Failed to build the package

Do you want to see the log file?  [y]:
```

Logs:

``` bash
dpkg-deb: error: parsing file '/var/tmp/tmp.EG6qgSt85J/package/DEBIAN/control' near line 7 package 'pngquant':
 error in 'Version' field string '2.7.2-1%{?dist}': invalid character in revision number
```

**Comment by pornel** [comment]
I don't know much about debs. Does it complain about `%{?dist}` appended to the version? 

Do you know how the correct package definition should look like?

**Comment by codefuhrer** [comment]
Yes, only commas (no spaces between them) and parenthesis are allowed. Example config:
```bash
10 - Requires: [ libc6,libgcc1 (>= 1:4.1.1),libncurses5,libpcap0.8 (>= 0.9.8) ]
```
Same thing with `Release`.

**Comment by pornel** [comment]
For `Requires`, etc. I have multiple lines, no commas:

https://github.com/pornel/pngquant/blob/master/pngquant.spec

Is that correct?

**Comment by codefuhrer** [comment]
Your .spec file has some kind of wildcard tags, which have to be replaced during the build (like `%{?dist}`). Seems like checkinstall takes these values "as is".

For example, `zlib%{?isa}` has to be transformed into `zlib(x86-64)`, but checkinstall uses the raw `zlib%{?isa}` value as requirement, which is incorrect and invalid.

Unfortunately, I don't know what's the best way to fix this.

**Comment by Roy-Orbison** [comment]
@pornel Could you hint at strings we'd have to use in those places? I tried editing the fields but end up with errors like this:

    `Depends' field, syntax error after reference to package `zlib1g'

**Comment by Roy-Orbison** [comment]
Worked around this by changing *Release* to `1` (simply removed suffix), and entered nothing for *Depends* (which I know is not the Right Way™).

Voilà; it's usable.

**Comment by pornel** [comment]
There's a new build system now, so I'm closing this.
