### ISSUE TITLE
reducing to 2 colors with 2.7.2 vs. 2.5.1

### ISSUE THREAD

**Issue by rcanavan** [pornel/pngquant#207]
A test image in our integration tests is dithered significantly differently by pngquant 2.7.2 as compared to pngquant 2.5.1 when generating a 2 color image.  I would argue that the result with 2.5.1 is a better visual representation of the original.

Original ![orig](https://cloud.githubusercontent.com/assets/4719149/17100395/62bcca36-526e-11e6-9e30-b16b3dd3a770.png)
2.5.1 ![251](https://cloud.githubusercontent.com/assets/4719149/17100383/5794be52-526e-11e6-892e-a9ccfcbcbef5.png)
2.7.2 ![272](https://cloud.githubusercontent.com/assets/4719149/17100387/5a1ff72c-526e-11e6-92a0-48a352ef4c31.png)

**Comment by pornel** [comment]
Algorithm used by pngquant is not suitable for small number of colors. For 8 colors or less see http://people.eecs.berkeley.edu/~dcoetzee/downloads/scolorq/

**Comment by rcanavan** [comment]
Thanks, we're note seriously using such small numbers of colors in production, this was just a test that failed. Since this is out of scope for pngquant, I'll close this issue.

**Comment by petrdiblik** [comment]
Does scolorq work for you on newer Windows? It does not for me on 8.1.
