### ISSUE TITLE
PNG transparency has white border/halo

### ISSUE THREAD

**Issue by ontick** [pornel/pngquant#208]
Hi, I am a Unity3D game programmer. I use pngquant to compress png file,  and then use Unity3D's Texture2D.LoadImage() to load the compressed png file.
But in U3D GamePlay, the png appears white border/halo.
I found a solution about this, please refer to :
http://answers.unity3d.com/questions/238922/png-transparency-has-white-borderhalo.html#answer-949217

That solution's code:
 //=========================================================================
 // Copy the values of adjacent pixels to transparent pixels color info, to
 // remove the white border artifact when importing transparent .PNGs.
 public static void FixTransparency(this Texture2D texture)
 {
     Color32[] pixels = texture.GetPixels32();
     int w = texture.width;
     int h = texture.height;
     
     for     (int y = 0; y < h; y++) {
         for (int x = 0; x < w; x++) {
             int idx    = y * w + x;
             Color32 pixel = pixels[idx];
             if (pixel.a == 0) {
                 bool done = false;
                 if (!done && x > 0)   done = TryAdjacent(ref pixel, pixels[idx - 1]);        // Left   pixel
                 if (!done && x < w-1) done = TryAdjacent(ref pixel, pixels[idx + 1]);        // Right  pixel
                 if (!done && y > 0)   done = TryAdjacent(ref pixel, pixels[idx - w]);        // Top    pixel
                 if (!done && y < h-1) done = TryAdjacent(ref pixel, pixels[idx + w]);        // Bottom pixel
                 pixels[idx] = pixel;
             }
         }
     }
     
     texture.SetPixels32(pixels);
     texture.Apply();
 }
 
 private static bool TryAdjacent(ref Color32 pixel, Color32 adjacent)
 {
     if (adjacent.a == 0) return false;
     
     pixel.r = adjacent.r;
     pixel.g = adjacent.g;
     pixel.b = adjacent.b;
     return true;
 }
//=========================================================================

But these codes cost too much, and slowed down the game.

So could you please help me add this algorithm to pngquant with a switch?

Thank you very much.

**Comment by pornel** [comment]
It looks like you've run into the problem of blending colors in regular RGBA color space, instead of using **premultiplied alpha** color space.

This site has full description of the problem and solutions:

http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/

**Comment by ontick** [comment]
Thank you, pornel. I viewed that article. But I find that, if I use the original png file, the result is ok. If I use the compressed file by pngquant, the result is bad.
So I guess there is something difference between the original and the compressed png file at the border.
Could you please help me find out the reason? 
Thank you very much!

**Comment by pornel** [comment]
Your image probably has meaningful RGB values with alpha = 0 (equivalent to "bleeding a texture" example from the article under "Weak solutions"), and conversion clears RGB values of pixels with alpha = 0, because when alpha channel is correctly used, these values are impossible to see.

pngquant works in premultiplied alpha color space and is unable to preserve invisible RGB values.

The bleed hack would be very detrimental to quality of PNG8 images, and I don't think it's feasible to have it as part of the image if you care about file size or quality.

I strongly suggest fixing rendering to use premultiplied alpha. If you can't fix rendering, then you should look into applying the "bleed" workaround from the article as a preprocessing step after PNG decompression, but before rendering.

**Comment by ontick** [comment]
Hi pornel, thank you for your suggestions. I tried them, but they lead to another problem, reduced efficiency. I have more than 20 pngs need to load at one time when game play, so the best solution is preprocessing png before import them to the game editor.

So could you please help me add a param to the pngquant? eg, retain one pixel, that is to say, retain the RGB values of one pixel around the alpha=0 area; or remove one pixel, that is to say, remove the outter one pixel around the image.

Thank you very much.

**Comment by pornel** [comment]
It's not possible in pngquant2, because color model used everywhere is r*a, g*a, b*a, a, which means pngquant2 throws away RGB values when a=0.

Changing it to r,g,b,a would make it very inefficient, as pngquant 1.0. Try using pngquant 1.0 (from year 2000) to compare :)

**Comment by pornel** [comment]
Actually, I have an idea - change some transparent pixels to slightly non-transparent (alpha = 1).

**Comment by ontick** [comment]
"change some transparent pixels to slightly non-transparent (alpha = 1)"
That's great! But it's horrible to change it manually, cause we have more than 1000 pngs to change.
So can somehow change it automatically?

**Comment by pornel** [comment]
You could write a program that reads a PNG, edits alpha, and saves the PNG.

**Comment by ontick** [comment]
Thank you so much, pornel. With your opinion, I found a way to solve this problem.  Thank you again.

**Comment by pornel** [comment]
Cool :)
