### ISSUE TITLE
less output quality for transparent images in 2.7.2

### ISSUE THREAD

**Issue by MaikWagner** [pornel/pngquant#209]
Hi,

there is a salient quality reduction of quantized images with gradient transparency in pngquant-2.7.2. Can be reconstructed on command line:
```shell
$ pngquant alphatest_original.png -o alphatest_quantized.png
```

With version 2.7.2 you can recognize a rippled pattern, which is much less in 2.5.1 at nearly the same file size.

Original:
![alphatest_original](https://cloud.githubusercontent.com/assets/7701966/17322263/ff3b7392-589c-11e6-9295-4f0fba4bb5d8.png)
v2.5.1:
![alphatest_q251](https://cloud.githubusercontent.com/assets/7701966/17322264/ff3b82e2-589c-11e6-844c-7454496fc4d2.png)
v2.7.2:
![alphatest_q272](https://cloud.githubusercontent.com/assets/7701966/17322265/ff43981a-589c-11e6-812d-afacc6d56e6e.png)

**Comment by pornel** [comment]
2.7.3 should look like this: ![smooth](https://cloud.githubusercontent.com/assets/72159/17419551/e4667508-5a95-11e6-9a97-4aea075957fa.png)

**Comment by MaikWagner** [comment]
Works fine, thx!
