### ISSUE TITLE
Quick questions: png8 compress performance

### ISSUE THREAD

**Issue by wangruowr** [pornel/pngquant#210]
Hi,

we are now using a very old version of libimagequant (2.1.x), and now 2.6.0 is released.
By comparing these two releases, are there any key features in performance improving? Sorry to say that in old times it is limited to use the png8 compression to 256*256 threshold because of the performance issue, with respect. now bigger png files are requested to be compressed. 

-- we are not sure if we can get enough benefit by upgrading the library, or more work should be done at application, please advise!
-- according to our current use, 2.1.x is quite a stable version, what's the latest stable version of libimagequant?
-- is there any benchmark data about the current library for us to refer to?

Looking forward to your reply,
Thanks!

Baron

**Comment by pornel** [comment]
I keep versions of pngquant and libimagequant the same.

There has been a major change in remapping algorithm between 2.1 and 2.6. It has fixed several bugs, but performance-wise it's probably similar.

By default the library is configured to be slow, but maximize quality. If you prefer it to be faster, you can set desired speed:

https://pngquant.org/lib/#liq_set_speed

**Comment by wangruowr** [comment]
Thanks for the suggestion!
I will have a try
