### ISSUE TITLE
Linkage problem with shared lib and SuSE Linux

### ISSUE THREAD

**Issue by axelrose** [pornel/pngquant#214]
I'd like to compile pngquant from source under SuSE Linux but cannot succeed. Any ideas?

This is what tried:

```
$ env | grep PKG
PKG_CONFIG_LIBDIR=/opt/tools/ImageMagick-6.9.5-9/lib
PKG_CONFIG_PATH=/opt/tools/ImageMagick-6.9.5-9/lib/pkgconfig

$ ./configure --prefix=/opt/tools/pngquant-2.7.2

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.6.24)
      zlib: shared (1.2.8)
     lcms2: shared (2.8)

$ make test
make -C lib static
make[1]: Entering directory `/root/image-service-tools/dev/pngquant/lib'
make[1]: Nothing to be done for `static'.
make[1]: Leaving directory `/root/image-service-tools/dev/pngquant/lib'
gcc test/test.o lib/libimagequant.a -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I/opt/tools/ImageMagick-6.9.5-9/include/libpng16   -I/opt/tools/ImageMagick-6.9.5-9/include   -I/opt/tools/ImageMagick-6.9.5-9/include   -DUSE_LCMS=1 -L/opt/tools/ImageMagick-6.9.5-9/lib -lpng16   -L/opt/tools/ImageMagick-6.9.5-9/lib -lz   -L/opt/tools/ImageMagick-6.9.5-9/lib -llcms2   -lm -o test/test
./test/test.sh ./test pngquant test/test
make: *** [test] Error 1

$ ldd pngquant
        linux-vdso.so.1 =>  (0x00007fffa5fff000)
        libpng16.so.16 => not found
        libz.so.1 => /lib64/libz.so.1 (0x00007f141ae19000)
        liblcms2.so.2 => not found
        libm.so.6 => /lib64/libm.so.6 (0x00007f141aba0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f141a828000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f141b061000)

$ export LD_LIBRARY_PATH=/opt/tools/ImageMagick-6.9.5-9/lib/

$ make test
make -C lib static
make[1]: Entering directory `/root/image-service-tools/dev/pngquant/lib'
make[1]: Nothing to be done for `static'.
make[1]: Leaving directory `/root/image-service-tools/dev/pngquant/lib'
./test/test.sh ./test pngquant test/test
2.7.3 (August 2016)
OK
```

I looks to me as if the result just forget the location of the shared libraries. If I enforce this with LD_LIBRARY_PATH (which is not a viable solution for my runtime environment) all works as expected.

Cheers, Axel.

**Comment by pornel** [comment]
What do you get when you run

```sh
pkg-config --libs libpng
```
?

**Comment by sergiomb2** [comment]
Hello , https://github.com/pornel/pngquant/pull/183  , build png with shared libs is not completed (but could be a time to complete) .  
yes, you need add 

     export LD_LIBRARY_PATH="$(pwd)/lib:$LD_LIBRARY_PATH" 

but just if you use 

     make bin.shared 
     make test.shared

please take a look in https://pkgs.fedoraproject.org/cgit/rpms/pngquant.git/tree/pngquant.spec

**Comment by axelrose** [comment]
_pkg-config_ finds the dependency. It is seemingly used in the configuration, see log above.
```
pkg-config  --libs libpng
-L/opt/tools/ImageMagick-6.9.5-9/lib -lpng16
```

`make test.shared` works if I have LDD_LIBRARY_PATH set but failes otherwise.

For me it looks as if a simple compiler switch is missed which would leave the reference to the used shared libraries in the executable. This works well for me in my ImageMagick build but I cannot find out how ...


Regards, Axel.

**Comment by pornel** [comment]
I would not expect changes to `LD_LIBRARY_PATH` to be needed for linking with `libpng`.

If `pkg-config` says to use ImageMagick's libs, but they don't work, then I think it's a problem with IM/pkg-config on your system. Maybe you need to run `ldconfig`?

**Comment by sergiomb2** [comment]
with https://github.com/pornel/pngquant/pull/245 , you got the solution

```
-	./test/test.sh ./test $(BIN) $(TESTBIN)
+	LD_LIBRARY_PATH="lib" ./test/test.sh ./test $(BIN) $(TESTBIN)
```
