### ISSUE TITLE
Warning: this 'else' clause does not guard

### ISSUE THREAD

**Issue by zedxxx** [pornel/pngquant#215]
I have few warnings due compile `libimagequant.c` on Windows with MinGW-w64 (gcc version 6.2.0):

> pngquant/lib/libimagequant.c: In function 'get_dithered_pixel':
> pngquant/lib/libimagequant.c:1137:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
>      else if (px.r + sr < max_underflow) ratio = MIN(ratio, (max_underflow-px.r)/sr);
>      ^~~~
> pngquant/lib/libimagequant.c:1138:10: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
>           if (px.g + sg > max_overflow)  ratio = MIN(ratio, (max_overflow -px.g)/sg);
>           ^~
> pngquant/lib/libimagequant.c:1139:5: warning: this 'else' clause does not guard... [-Wmisleading-indentation]
>      else if (px.g + sg < max_underflow) ratio = MIN(ratio, (max_underflow-px.g)/sg);
>      ^~~~
> pngquant/lib/libimagequant.c:1140:10: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
>           if (px.b + sb > max_overflow)  ratio = MIN(ratio, (max_overflow -px.b)/sb);
>           ^~

All they about this code:

> ```
> // allowing some overflow prevents undithered bands caused by clamping of all channels
>      if (px.r + sr > max_overflow)  ratio = MIN(ratio, (max_overflow -px.r)/sr);
> else if (px.r + sr < max_underflow) ratio = MIN(ratio, (max_underflow-px.r)/sr);
>      if (px.g + sg > max_overflow)  ratio = MIN(ratio, (max_overflow -px.g)/sg);
> else if (px.g + sg < max_underflow) ratio = MIN(ratio, (max_underflow-px.g)/sg);
>      if (px.b + sb > max_overflow)  ratio = MIN(ratio, (max_overflow -px.b)/sb);
> else if (px.b + sb < max_underflow) ratio = MIN(ratio, (max_underflow-px.b)/sb);
> ```

**Comment by zedxxx** [comment]
You can fix it:

> 
>     // allowing some overflow prevents undithered bands caused by clamping of all channels
>            if (px.r + sr > max_overflow)  { ratio = MIN(ratio, (max_overflow -px.r)/sr); }
>     else { if (px.r + sr < max_underflow) { ratio = MIN(ratio, (max_underflow-px.r)/sr); } }
>            
>            if (px.g + sg > max_overflow)  { ratio = MIN(ratio, (max_overflow -px.g)/sg); }
>     else { if (px.g + sg < max_underflow) { ratio = MIN(ratio, (max_underflow-px.g)/sg); } }
>            
>            if (px.b + sb > max_overflow)  { ratio = MIN(ratio, (max_overflow -px.b)/sb); }
>     else { if (px.b + sb < max_underflow) { ratio = MIN(ratio, (max_underflow-px.b)/sb); } }

or 

>     // allowing some overflow prevents undithered bands caused by clamping of all channels
>            if (px.r + sr > max_overflow)  ratio = MIN(ratio, (max_overflow -px.r)/sr);
>     else { if (px.r + sr < max_underflow) ratio = MIN(ratio, (max_underflow-px.r)/sr); }
>            
>            if (px.g + sg > max_overflow)  ratio = MIN(ratio, (max_overflow -px.g)/sg);
>     else { if (px.g + sg < max_underflow) ratio = MIN(ratio, (max_underflow-px.g)/sg); }
>            
>            if (px.b + sb > max_overflow)  ratio = MIN(ratio, (max_overflow -px.b)/sb);
>     else { if (px.b + sb < max_underflow) ratio = MIN(ratio, (max_underflow-px.b)/sb); }

**Comment by pornel** [comment]
Thanks

**Comment by tavvfiq** [comment]
thanks bor
