### ISSUE TITLE
Reduce to 256 colors by processing colors of multiple images

### ISSUE THREAD

**Issue by RyanBram** [pornel/pngquant#216]
Dear Kornel,

Let's say I have 3 images that I want their colors to be reduced into about 256 color.But I don't want each images to have their own 256 color palette, instead I prefer them to share those 256 colors in every images. My current approach is by combining those 3 images into a single image, reduce the color to 256 with PNGquant, then splitting that image into three individual images again.

That method is not a big deal if I just want to convert few images, but if I have ten or more images, it starts to become hard task.

Is there a way to simplifiy that method in PNGquant? or can you consider to implement such feature?
## 

Best regards.
Ryan Bram

**Comment by pornel** [comment]
I'm aware there's a need for this.

Currently the solution is:

* use the callback version of image creation https://pngquant.org/lib/#liq_image_create_custom to combine images on the fly (assuming they have the same width)
* save palette *before* remapping any results (contrary to what the docs say)
* remap images individually as usual, reusing the `liq_result` object

**Comment by RyanBram** [comment]
Currently I am using ImageMagick for helping my task, the following Windows batch script may useful for someone who need it:

`convert.exe" -append "originalimagepath/*.png" png:- | pngquant.exe" --speed n 256 | convert.exe" png:- -crop (original_width)x(original_height) "resultpath/resultname_%%d.png"`

Thanks Kornel for the soluton.

Best regards,
RyanBram

**Comment by rolftimmermans** [comment]
Wouldn't saving the palette before remapping ignore some improvements to the palette that are made during the remapping stage? Is that intentional?

**Comment by pornel** [comment]
Improvement to the palette done during remapping is specific to the one image that was remapped. If you want a single palette that is suitable for many images, you can't have it tuned for only one of the images.

**Comment by rolftimmermans** [comment]
The question, I guess, is: Wouldn't those improvements be necessary for a good quality quantisation of multiple images too, but instead taking all images into account? I understand that this is not possible with the API right now, but I was just wondering what the ideal situation would be.

**Comment by pornel** [comment]
You can achieve the same by setting speed to a slower setting.

**Comment by pornel** [comment]
I could expose pngquant's histogram to make combining of multiple images easier/lower-mem.

**Comment by pornel** [comment]
I've added Histogram API in 2.8.0

https://pngquant.org/lib/#liq_histogram_quantize

**Comment by LuminairPrime** [comment]
> It's possible to efficiently generate a single palette that is optimal for multiple images, e.g. for an APNG animation. This is done by collecting statistics of images in a liq_histogram object.

@kornelski I've been researching the best practice for making an animated image, and so far it seems to be PNG files optimized by pngquant, then compressed by pingo/ect/oxipng, then formed into APNG with ffmpeg. My problem is that a shared palette doesn't appear to be available in the command line of pngquant. The author of apngasm suggests using apngdis to create a single image out of the image set, then apply pngquant to that, then build the APNG with apngasm. But I don't think the best practice should be using a proprietary intermediary format.

If I'm on the right page about all that, should I be creating a feature quest here to have a --sharedpalette option added to pngquant for APNG creation?

**Comment by kornelski** [comment]
I wrote https://gif.ski for animations. You’ll get better quality thanks to per-frame palettes and maybe even better compression from lossy LZW.
