### ISSUE TITLE
Configure Script Incompatible with Solaris 10 Environment

### ISSUE THREAD

**Issue by surighanta** [pornel/pngquant#217]
Hi Pornel,

performance and the output of the tool are really impressive. But we got to run this in Solaris 10 server for which compiled software is not provided.

We are trying to compile this in Solaris 10 and configure script itself is failing with errors due to advanced command line option provided for grep and find command etc., 

I Assume this is not verified Solaris 10 environment.

Can you help us with that.

**Comment by sergiomb2** [comment]
Hello what are the errors ? , have you a fix for your system ? 
Thanks

**Comment by surighanta** [comment]
Errors are 

1. _-quit_ option for find command
2.  -E, -m, -o, -1 not supported in in grep command
3. Shell script syntax errors

Snippet:

grep: illegal option -- E
grep: illegal option -- o
Usage: grep -hblcnsviw pattern file . . .

  Compiler: /usr/sfw/bin/gcc
     Debug: no
grep: illegal option -- E
grep: illegal option -- m
grep: illegal option -- 1
Usage: grep -hblcnsviw pattern file . . .
./configure: line 271: [: auto: integer expression expected
./configure: line 279: [: auto: integer expression expected
    OpenMP: no
    libpng: error ... not found (try: `apt-get install libpng16-dev` or `apt-get install libpng-dev` or `yum install libpng-devel`)

I could not manage to fix them. I tried hard coding few things in the config script but that did not help.

**Comment by pornel** [comment]
Fortunately `grep -Eo` is used only for cosmetic reasons. The real problem is that you don't have working `libpng` or `pkg-config` on your system.

**Comment by surighanta** [comment]
I have installed libpng and zlib dependencies. But, since the find command is failing because of -quite option, script is assuming that it is not found. Same happening for following dependencies also.

However removal of -quite from find command also did not help. 

i have tried with libpng shared library, copying libpng source to current directory also.

**Comment by pornel** [comment]
Solaris looks hopelessly broken.

Maybe another aproach:

1. Run ./configure on Linux
2. Copy `config.mk` to Solaris
3. Edit `config.mk` manually to correct settings and paths to libraries

**Comment by surighanta** [comment]
- Issue was with "pkg-config" and PKG_CONFIG_PATH. 
- Later we had some cosmetic issues with install, bu we managed them by running the commands manually without unsupported CLI options.

We are able to compile and install it now. Thanks for the support! Issue Closed.
