### ISSUE TITLE
Unknown Error in production

### ISSUE THREAD

**Issue by skgitter** [pornel/pngquant#220]
Hi I sometimes get this error in my production server. Could not be able to fix it. Please help me out.

Issue is not continues issue , sometimes works sometimes not !!

`{ [Error: Command failed: /opt/app/control-panel/node_modules/pngquant-bin/vendor/pngquant --output /tmp/b1a0d900-1c72-4b9f-b7ea-e5ee3458dbb3 /tmp/7f748fa1-8f7c-47b8-8522-653c8
35afb1b --quality 65-80
]
  killed: false,
  code: 99,
  signal: null,
  cmd: '/opt/app/control-panel/node_modules/pngquant-bin/vendor/pngquant --output /tmp/b1a0d900-1c72-4b9f-b7ea-e5ee3458dbb3 /tmp/7f748fa1-8f7c-47b8-8522-653c835afb1b --quality 
65-80',
  stdout: '',
  stderr: '' }
`

Caller code ::

`return imagemin.buffer(buffer, {
            plugins : [
                imageminMozjpeg(),
                imageminPngquant({quality: '65-80', optimizationLevel:1})
            ]
        })
        .then(function (data) {
            console.log("response from image optimization");
            console.log( data );
            // code to upload image to aws s3 storage
        });`

**Comment by pornel** [comment]
Return code 99 means `--quality 65-80` could not be met, i.e. the image ended up with quality below 65.

**Comment by skgitter** [comment]
@pornel How can i solve this in production. Where I need to add this check ?

**Comment by pornel** [comment]
If you're passing `--quality 65-80` yourself, then either use `--quality 0-80` or check status code returned from the executable.

If you're using a node library that launches the command for you, then ask the author of the node library to fix this.

**Comment by skgitter** [comment]
@pornel Thanks for your reply , it works !! Can you please suggest one more thing , how can i restrict user to upload images between 65-80 ? I mean how can I check quality of an image out of the box ?

**Comment by pornel** [comment]
This setting is not a property of the image, but an instruction for the conversion, so you can't check what quality an image has (that is not possible without having a second image that is the reference for the quality).
