### ISSUE TITLE
Why output different reduction for same file when in diff OS

### ISSUE THREAD

**Issue by snasc** [pornel/pngquant#225]
When I use nodejs lib `imagemin-pngquant`, I found this problem, then I directly use the `pngquant` binary, still this.

In OS X, there's an `a3.png` with size 2100 bytes, I run `pngquant a3.png`, get a file `a3-fs8.png` with 723 bytes (quality good), almost **66%** reduction. PS: pngquant 2.7.1

With the same `a3.png`, in a CentOS 6.5, run `pngquant a3.png` get a file `a3-fs8.png` with 1623 bytes, just **22%** reduction. PS: still pngquant 2.7.1

And then I tried pngquant 2.7.2 & 2.3.6, all compiled from source, all get almost 22% reduction. May I set something wrong?

The 2.3.6 in CentOS:

    pngquant, 2.3.6 (March 2015), by Greg Roelofs, Kornel Lesinski.
       Compiled with SSE instructions.
       Using libpng 1.2.49 with Little CMS color profile support.

    WARNING: Your version of libpng is outdated and may produce corrupted files.
    Please recompile pngquant with the current version of libpng (1.6 or later).

then 2.7.2:

    pngquant, 2.7.2 (June 2016), by Kornel Lesinski, Greg Roelofs.
       Color profiles are supported via Little CMS. Using libpng 1.6.26.

    usage:  pngquant [options] [ncolors] -- pngfile [pngfile ...]
            pngquant [options] [ncolors] - >stdout <stdin

Actually, I also try it in Ubuntu 14.04, the pngquant 2.7.1, get reduction 22% too.

**Comment by pornel** [comment]
Generally pngquant is *not* expected to have repeatable results across systems. There are multiple reasons for this, mainly:

- different version of libpng. You never use libpng 1.2 — it's really old and has known bugs affecting pngquant. This affects file size.
- different floating-point implementation. Compilers, SSE and fast math flags allow computations to give slightly different results, which can snowball into different palette and dithering patterns, sometimes visibly affecting results.

**Comment by snasc** [comment]
Hi, thank you for reply. But the 22% reduction is Unacceptable, there must be something wrong.

In Ubuntu 14.04, then i get a 2.0.1 installed by `apt-get install`, it's ok, get the 66% reduction, the a3-fs8.png with 723 bytes.

    pngquant, 2.0.1 (September 2013), by Greg Roelofs, Kornel Lesinski.
       DEBUG (slow) version.
       Compiled with SSE2 instructions.
       Compiled with libpng 1.2.49; using libpng 1.2.50.

    usage:  pngquant [options] [ncolors] [pngfile [pngfile ...]]

So, seems like if it's compiled from source by me, then it has the problem. Below is a config.mk in CentOS:

    # auto-generated by configure
    PREFIX = /usr/local
    VERSION = 2.7.2  
    CC = gcc
    CFLAGS = -O3 -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wn
    LDFLAGS =  ../libpng-1.6.26/.libs/libpng16.a -lz   -llcms2   -lm
    COCOA_READER = 0

Is there anything wrong?

**Comment by jibsen** [comment]
I notice the versions you compile yourself appear to include lcms, while the 2.0.1 you link as giving you 66% does not. I wonder if this makes any difference for your image?

**Comment by snasc** [comment]
@jibsen , when i found the problem and start compiling by myself, there's no lcms installed. And the problem still there, so I specially add the lcms2, then no help. So i think that's not the reason.

**Comment by snasc** [comment]
[UPDATE]

Inspired by the 2.0.1 from apt-get, I got the 2.0.1 src and compiled it (Ubuntu 14.04), It's working!

    pngquant, 2.0.1 (September 2013), by Greg Roelofs, Kornel Lesinski.
       Compiled with SSE2 instructions.
       Compiled with libpng 1.6.26; using libpng 1.6.26.

    usage:  pngquant [options] [ncolors] [pngfile [pngfile ...]]

I get the 723 bytes `a3-fs8.png`, in OS X, it's exactly 723.

    -rw-rw-r-- 1 snasc snasc  723 Nov 19 17:05 a3-fs8.png
    -rw-r--r-- 1 snasc snasc 2100 Nov 19 16:31 a3.png

Then in CentOS, I got the 2.0.2 src and compiled it, also solved the `libpng16.so.16: cannot open shared object file: No such file or directory` problem. It works too!

    [snasc@sftp pngquant-2.0.2]$ ./pngquant -fv a3.png 
    a3.png:
      read 3KB file corrected for gamma 2.2
      made histogram...58 colors found
      eliminated opaque tRNS-chunk entries...23 entries transparent
      mapped image to new colors...MSE=0.000 (Q=100)
      writing 58-color image as a3-fs8.png
    No errors detected while quantizing 1 image.

So, maybe the systems I used is too old, just match the pngquant 2.0.x. However, I will use 2.0.2, I really need solve this for now.

**Comment by pornel** [comment]
I'm measuring quality and file sizes produced by every release, and each release is better *on average*, so using older version will give you worse results in general.

For example all versions older than 2.5 use dithering algorithm with a bug that sometimes causes color streaks.

If you're talking about 33% difference on a 1KB file then it's very likely to be caused by different version of libpng, e.g. preserving of metadata will differ depending on pngquant and libpng versions.

**Comment by snasc** [comment]
I mostly use the libpng 1.6.26 compiled from source.

Do you use or test pngquant in a Ubuntu or CentOS, and which version of libpng do you use?

**Comment by pornel** [comment]
I don't use any Linux version myself. 1.6 is required for full functionality. 1.4 is partially supported. 1.2 is broken.

**Comment by snasc** [comment]
ok, I'll try different version of libpng, like 1.6.21, with the latest pngquant. And I'll test more images with the latest pngquant. If there's any good news, I'll remark it here.

Thanks again.
