### ISSUE TITLE
Who are all using pngquant for saving file size

### ISSUE THREAD

**Issue by imvetri** [pornel/pngquant#226]
We can have this thread maintained to keep track of companies using pngquant. subsequently I can help updating the information in the wiki of pngquant.

**Comment by pornel** [comment]
There are some companies mainly selling pngquant as a service, e.g. TinyPNG, Kraken, Cloudinary, Shortpixel.

I'm not keeping the full list though. I'm not sure what the purpose of that would be.

**Comment by imvetri** [comment]
purpose: it may help new visitors how good this tool is for them.

**Comment by Cat5TV** [comment]
We'll be featuring _pngquant_ on [Category5 Technology TV](https://category5.tv/) sometime in January 2017. We'll also be using it to reduce filesize on our own PNG images on the official web site via an automated cron script that goes out to our CDN, checks filesizes, and shrinks files automatically.
