### ISSUE TITLE
How to create binary transparency?

### ISSUE THREAD

**Issue by RyanBram** [pornel/pngquant#230]
Hi, Kornel.

One of the most useful function of pngquant is I can create a GIF file that looks almost as good as PNG.
From my understanding, if the source image contains semi transparent area, pngquant will keep those semi transparent as possible, which unfortunately doesn't supported by GIF. Although many converter support conversion from PNG to GIF after it was quantized by pngquant, but the result of converting semi transparent area to binary transparent is not very good.

**Are there any features in pngquant to create binary transparency or would you implement it if there is no such feature?**

Thanks.

**Comment by pornel** [comment]
You can change the input image to have binary transparency.

**Comment by RyanBram** [comment]
Let's say I use ImageMagic's convert.exe to do the task you said.

How does it make my image looks better between using binary transparent image as input image **before using pngquant** and removing semi transparent **after using pngquant**?

I just feel that pngquant will do the task better than other software if it support binary transparent isn't it?

**Comment by pornel** [comment]
If you change transparency before giving the image to pngquant, then pngquant won't waste palette colors on any semi-transparencies. 

But the big question is why do you even convert PNG to GIF? It makes the file uglier *and* larger.

**Comment by RyanBram** [comment]
The reason is like yours.
You added lossy feature because of animation support in GIF, isn't it?
I also want to create animated GIF from PNGs, but cannot find a good way to remove their semi transparancies.

Anyway, thanks for the answers.
