### ISSUE TITLE
Linux CentOs 7 - installation

### ISSUE THREAD

**Issue by ozozm** [pornel/pngquant#231]
Used git clone --recursive https://github.com/pornel/pngquant.git in SSH after login. It successfully plonked the folder straight into root directory so i moved it to the /usr/local/bin which is apparently supposed to be the default.

Navigated to usr/local/bin/pngquant

"make" & "sudo make install" returns:  
-------------------------------------------------------------------------------------------------------------------
./configure: line 250: gcc: command not found
  Compiler: error ... gcc failed to compile anything (make sure it's installed and supports C99)

make: *** No rule to make target `config.mk', needed by `pngquant.o'.  Stop.

**Comment by pornel** [comment]
You should not move the folder or any files to `/usr/` yourself. Clone the folder to your home directory or `/tmp`.
 
> gcc failed to compile anything (make sure it's installed and supports C99)

You need to install gcc (the package may be called `build-essential`)

**Comment by sergiomb2** [comment]
Hi, if its help,  you got pngquant in epel7 repos  https://apps.fedoraproject.org/packages/pngquant

**Comment by ozozm** [comment]
For future readers with the same problem, I installed it using the yum command as follows...

sudo yum install gcc

yum install lib16-devel

sudo yum install pngquant

:)
