### ISSUE TITLE
outdated libpng on Debian Jessie?

### ISSUE THREAD

**Issue by MACscr** [pornel/pngquant#234]
If pngquant is available as a package for Jessie, why are its required packages not up to date as well? I would rather not have to compile pngquant on all my systems and have to manage those things manually. Is there an apt-get solution to this issue?

```
pngquant, 2.3.0 (July 2014), by Greg Roelofs, Kornel Lesinski.
   Compiled with libpng 1.2.50; using libpng 1.2.50.

WARNING: Your version of libpng is outdated and may produce corrupted files.
Please recompile pngquant with newer version of libpng (1.5 or later).
```

**Comment by pornel** [comment]
I don't know exactly why they built it with the buggy libpng. I guess it's might be an unfortunate combination of their policy and backwards-compatibility constraints.

However, Debian testing has *finally* upgraded libpng, so this problem will go away.

**Comment by MACscr** [comment]
In a couple years? Jessie is supported till 2020.

- Mark

**Comment by pornel** [comment]
You have 3-year-old version of pngquant with 7-year-old version of libpng. Don't use Debian if you want up-to-date software.

**Comment by sergiomb2** [comment]
this is a duplicated issue with https://github.com/pornel/pngquant/issues/174 ? you may try libpng 1.6 , check it please https://tracker.debian.org/pkg/libpng1.6

**Comment by rkyoku** [comment]
> You have 3-year-old version of pngquant with 7-year-old version of libpng. Don't use Debian if you want up-to-date software.

Hi @kornelski , I have exactly the same issue here, on Debian Jessie. Which distro do you advise for up-to-date packages? Ubuntu? Something else? I grew tired of all these dusty, buggy, and deprecated packages that I have all the time... :-/
