### ISSUE TITLE
Pipe output from imagick to pnquant?

### ISSUE THREAD

**Issue by matjazu** [pornel/pngquant#235]
Is it possible to pipe output from imagick's convert command to pngquant? I'm trying to convert jpg to png and then apply lossy compression with pngquant.

**Comment by pornel** [comment]
Yes

```sh
convert … | pngquant -
```

**Comment by matjazu** [comment]
I tried that, here is an example...
`convert test-image.jpg -quality 100 | pngquant 150 --speed=8 > new-test-image.png`
 ...or even simpler...
`convert test-image.jpg | pngquant 150 > new-test-image.png`
... and it is not working, any ideas? 

When I ran commands separately and output it into file, there is no problem / error.

**Comment by jibsen** [comment]
You have to tell the various programs to read and write from stdin/stdout. Something along the lines of:

~~~.sh
convert test-image.jpg png:- | pngquant - >new-test-image.png
~~~

**Comment by matjazu** [comment]
@jibsen Thank you very much, I missed that totally.
