### ISSUE TITLE
How to use the PHP script on the pngquant website

### ISSUE THREAD

**Issue by ozozm** [pornel/pngquant#236]
I am trying to use the file upload script from w3schools with the pngquant compression script. I have omitted some of the verification code from the upload script for ease of example, I have also added a few lines to remove existing files by the same name. The full script for each can be found with the links below...

w3schools php file upload script - http://www.w3schools.com/php/php_file_upload.asp

pngquant php file compression script - http://pngquant.org/php.html

Ok, so an attempt to combine the two. The pngquant function asks for $path_to_png_file as the first parameter and the "Convert PNG files on the fly" script asks for $path_to_uncompressed_file as the first parameter, should these not be the same?

What I am trying to achieve is a start to end approach of how to easily implement pngquant. The problem I see again and again is, hard working people who spend a lot of time make a wonderful product but forget to make it simple to actually use. If the following is inefficient, is anyone interested in writing a better version?

```
<?php

$existingImage = 'put name of existing file here'; // existing file name if applicable

$target_dir = "uploads/";
$target_file = $target_dir . basename($_FILES["fileToUpload"]["name"]);
$uploadOk = 1;
$imageFileType = pathinfo($target_file,PATHINFO_EXTENSION);

// Check if image file is a actual image or fake image - Omitted
// Check if file already exists - Omitted
// Check file size - Omitted
// Allow certain file formats - Omitted

// Additional code to remove file by the same name
if (file_exists($target_file)) {unlink($target_file);}
	
	$removeOld = 'uploads/' . $existingImage; 
	
	unlink($removeOld);

// Check if $uploadOk is set to 0 by an error
if ($uploadOk == 0) {
    echo "Sorry, your file was not uploaded.";
// if everything is ok, try to upload file
} else {
    if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $target_file)) {
//      echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";


/* -- pngquant -- */

// function
function compress_png($path_to_png_file, $max_quality = 90)
{
    if (!file_exists($path_to_png_file)) {
        throw new Exception("File does not exist: $path_to_png_file");
    }

    // guarantee that quality won't be worse than that.
    $min_quality = 60;

    // '-' makes it use stdout, required to save to $compressed_png_content variable
    // '<' makes it read from the given file path
    // escapeshellarg() makes this safe to use with any path
    $compressed_png_content = shell_exec("pngquant --quality=$min_quality-$max_quality - < ".escapeshellarg(    $path_to_png_file));

    if (!$compressed_png_content) {
        throw new Exception("Conversion to compressed PNG failed. Is pngquant 1.8+ installed on the server?");
    }
//    return $compressed_png_content;
}
    } else {
        echo "Sorry, there was an error uploading your file.";
    }

$path_to_uncompressed_file = $target_file;
$path_to_compressed_file = $target_dir . 'test-small.png';

// this will ensure that $path_to_compressed_file points to compressed file
// and avoid re-compressing if it's been done already
if (!file_exists($path_to_compressed_file)) {
    file_put_contents($path_to_compressed_file, compress_png($path_to_uncompressed_file));
}

// and now, for example, you can output the compressed file:
header("Content-Type: image/png");
header('Content-Length: '.filesize($path_to_compressed_file));
readfile($path_to_compressed_file);
}

?>
```
The output from this script is a 0kb file "test-small.png" in uploads/

I found this, which given the script on the pngquant website I can't believe how uncomplicated it is.

`<?php system('pngquant --quality=85 image.png'); ?>`

It outputs a an optimised image of a different name. How can we add a minimum quality and overwrite the existing using $file_to_process as "image.png"?

**Comment by pornel** [comment]
You can use this to optimize in place:

```php
<?php system('pngquant --ext=.png --force --quality=85 image.png'); ?>
```

Please be careful when passing filename. If you don't use `escapeshellarg()`, someone will be able to take over your server by uploading file with a special filename.

**Comment by ozozm** [comment]
Thanks Pornel, a much simpler solution :) Like this?

<?php system('pngquant --ext=.png --force --quality=85 escapeshellarg(image.png)'); ?>

**Comment by pornel** [comment]
```php
<?php system('pngquant --ext=.png --force --quality=85 ' .  escapeshellarg($image_filename)); ?>
```

**Comment by ozozm** [comment]
Cheers, so tell me mate, if it can be done so simply, why do you post that elaborate script in the pngquant website? It sent me in completely the wrong direction.

**Comment by pornel** [comment]
Because the script is more efficient and handles errors.

**Comment by ozozm** [comment]
Ok well thanks for everything, appreciate it.
