### ISSUE TITLE
releases lib/ missing

### ISSUE THREAD

**Issue by CvH** [pornel/pngquant#238]
With the introducing of `lib/` as git submodule your release packages did not include any content at `lib/` anymore and thereby you can't build pngquant with just the release package. 
Looks like Github is not able to handle this properly :(

**Comment by pornel** [comment]
Please don't use GitHub tarballs. Official release packages with all files are here:

https://pngquant.org/releases.html

**Comment by CvH** [comment]
tx, I was missleaded from the homepage
![image](https://cloud.githubusercontent.com/assets/1355173/24715624/65018fd0-1a2c-11e7-987a-a0785f0e12cb.png)

**Comment by pornel** [comment]
Thanks. I've removed that link
