### ISSUE TITLE
pngquant won't work using PHP on a Mac

### ISSUE THREAD

**Issue by krompir2** [pornel/pngquant#240]
I am running a simple script to compress images in the current directory:

`echo $get_compress =  exec("find . -name '*.png' -exec  /usr/local/bin/pngquant --ext .png --force 256 {} \; 2>&1", $output); 
print_r($output); `

I am getting an error:

`/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIOArray ( [0] => dyld: Symbol not found: __cg_jpeg_resync_to_restart [1] => Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO [2] => Expected in: /Applications/XAMPP/xamppfiles/lib/libJPEG.dylib [3] => in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO ) `

I've searched intensively for a solution. The problem seem to stem from how OSX links libraries, but that is pretty much all i know.

Any idea how to handle this issue?

**Comment by pornel** [comment]
You have something in your environment/init scripts/server config that sets `DYLD_LIBRARY_PATH` (or `DYLD_FRAMEWORK_PATH `) environmental variable to a custom value, which is playing with fire and breaks all JPEG-related software due to peculiarities of Apple's private framework implementation.

Your option is to find and remove all overrides of library paths, or build a custom version of pngquant without Cocoa support.

**Comment by krompir2** [comment]
Thanks for a quick replay. I think I'm gonna go with "find and remove all overrides of library paths".
Does this mean I just grep my computer for DYLD_LIBRARY_PATH and DYLD_FRAMEWORK_PATH string and delete every line starting with export?

**Comment by pornel** [comment]
Maybe no the entire computer. Just your server config? Maybe print these variables (or see phpinfo()) for a hint where they're set?

**Comment by krompir2** [comment]
did sudo grep -rnwn . -e "DYLD_LIBRARY_PATH" on a /Applications/XAMPP folder.

I ended up commenting out export DYLD_LIBRARY_PATH in
`./xamppfiles/bin/envvars-std
./xamppfiles/bin/envvars
./xamppfiles/xampp`

After restarting apache, pngquant still doesn't work.


phpinfor() has 3 occurances of DYLD_LIBRARY_PATH
Under environment:
`DYLD_LIBRARY_PATH	/Applications/XAMPP/xamppfiles/lib:/Applications/XAMPP/xamppfiles/lib`
Under PHP variables:
`_SERVER["DYLD_LIBRARY_PATH"]
/Applications/XAMPP/xamppfiles/lib:/Applications/XAMPP/xamppfiles/lib`
Under Apache environment:
`DYLD_LIBRARY_PATH	/Applications/XAMPP/xamppfiles/lib:/Applications/XAMPP/xamppfiles/lib`

I am not sure what should I do with those values..



Ful results of grep:
`./bin/apr-1-config:41:SHLIBPATH_VAR="DYLD_LIBRARY_PATH"
./bin/envvars:21:if test "x$DYLD_LIBRARY_PATH" != "x" ; then
./bin/envvars:22:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib:$DYLD_LIBRARY_PATH"
./bin/envvars:24:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib"
./bin/envvars:26:export DYLD_LIBRARY_PATH
./bin/envvars-std:21:if test "x$DYLD_LIBRARY_PATH" != "x" ; then
./bin/envvars-std:22:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib:$DYLD_LIBRARY_PATH"
./bin/envvars-std:24:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib"
./bin/envvars-std:26:export DYLD_LIBRARY_PATH
Binary file ./bin/httpd matches
./bin/icu-config:318:LDLIBRARYPATH_ENVVAR="DYLD_LIBRARY_PATH"
grep: ./logs/cgisock.26131: Operation not supported on socket
./xamppfiles/bin/apr-1-config:41:SHLIBPATH_VAR="DYLD_LIBRARY_PATH"
./xamppfiles/bin/envvars:21:if test "x$DYLD_LIBRARY_PATH" != "x" ; then
./xamppfiles/bin/envvars:22:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib:$DYLD_LIBRARY_PATH"
./xamppfiles/bin/envvars:24:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib"
./xamppfiles/bin/envvars:26:export DYLD_LIBRARY_PATH
./xamppfiles/bin/envvars-std:21:if test "x$DYLD_LIBRARY_PATH" != "x" ; then
./xamppfiles/bin/envvars-std:22:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib:$DYLD_LIBRARY_PATH"
./xamppfiles/bin/envvars-std:24:  DYLD_LIBRARY_PATH="/Applications/XAMPP/xamppfiles/lib"
./xamppfiles/bin/envvars-std:26:export DYLD_LIBRARY_PATH
Binary file ./xamppfiles/bin/httpd matches
./xamppfiles/bin/icu-config:318:LDLIBRARYPATH_ENVVAR="DYLD_LIBRARY_PATH"
./xamppfiles/build/config_vars.mk:37:SHLIBPATH_VAR = DYLD_LIBRARY_PATH
./xamppfiles/build/libtool:228:variables_saved_for_relink="PATH DYLD_LIBRARY_PATH  GCC_EXEC_PREFIX COMPILER_PATH LIBRARY_PATH"
./xamppfiles/build/libtool:243:shlibpath_var=DYLD_LIBRARY_PATH
./xamppfiles/include/apr-1/apr.h:616:#define APR_DSOPATH "DYLD_LIBRARY_PATH"
Binary file ./xamppfiles/lib/instantclient/libclntsh.dylib matches
Binary file ./xamppfiles/lib/instantclient/libclntsh.dylib.11.1 matches
Binary file ./xamppfiles/lib/instantclient-11.2.0.3.0/libclntsh.dylib matches
Binary file ./xamppfiles/lib/instantclient-11.2.0.3.0/libclntsh.dylib.11.1 matches
Binary file ./xamppfiles/lib/libaprutil-1.0.dylib matches
Binary file ./xamppfiles/lib/libaprutil-1.a matches
Binary file ./xamppfiles/lib/libaprutil-1.dylib matches
Binary file ./xamppfiles/lib/libgettextlib-0.18.1.dylib matches
Binary file ./xamppfiles/lib/libgettextlib.a matches
Binary file ./xamppfiles/lib/libgettextlib.dylib matches
Binary file ./xamppfiles/lib/libltdl.3.1.0.dylib matches
Binary file ./xamppfiles/lib/libltdl.3.dylib matches
Binary file ./xamppfiles/lib/libltdl.a matches
Binary file ./xamppfiles/lib/libltdl.dylib matches
./xamppfiles/lib/perl5/5.16.3/darwin-thread-multi-2level/Config.pm:97:    ldlibpthname => 'DYLD_LIBRARY_PATH',
./xamppfiles/lib/perl5/5.16.3/darwin-thread-multi-2level/Config_heavy.pl:927:ldlibpthname='DYLD_LIBRARY_PATH'
./xamppfiles/lib/php/build/libtool.m4:1525:  shlibpath_var=DYLD_LIBRARY_PATH
Binary file ./xamppfiles/lib/php/extensions/no-debug-non-zts-20131226/oci8.a matches
Binary file ./xamppfiles/lib/php/extensions/no-debug-non-zts-20131226/oci8.so matches
grep: ./xamppfiles/logs/cgisock.26131: Operation not supported on socket
./xamppfiles/share/doc/gettext/examples/build-aux/csharpexec.m4:60:              CLIX_PATH_VAR=DYLD_LIBRARY_PATH
./xamppfiles/share/doc/gettext/examples/hello-c++-kde/admin/libtool.m4.in:1143:  shlibpath_var=DYLD_LIBRARY_PATH
./xamppfiles/share/icu/4.8.1.1/config/mh-darwin:39:LDLIBRARYPATH_ENVVAR = DYLD_LIBRARY_PATH
grep: ./xamppfiles/var/mysql/mysql.sock: Operation not supported on socket
./xamppfiles/xampp:163:	unset DYLD_LIBRARY_PATH
./xamppfiles/xampp:285:	unset DYLD_LIBRARY_PATH
./xamppfiles/xampp:452:    if test -z $DYLD_LIBRARY_PATH
./xamppfiles/xampp:454:	export DYLD_LIBRARY_PATH="$LIBRARY_PATH"
./xamppfiles/xampp:456:	export DYLD_LIBRARY_PATH="$LIBRARY_PATH:$DYLD_LIBRARY_PATH"`

**Comment by pornel** [comment]
Try overwriting it with [putenv](http://php.net/manual/en/function.putenv.php)

**Comment by krompir2** [comment]
I've started the computer today, with the commented out export settings from yesterday. I had to run `sudo apachectl start` and `sudo apachectl stop`, because the gui start didn't want to start.

I have no idea why gui restart button didn't actually restart server settings yesterday, but today am running pngquant on mac successfully.  Thank you so much for helping me out.

On a side note, I've measured the speed of compression, and it takes about 0.6s for mostly transparent 3800px x 3400px image. The size goes from 1.1MB to 450KB. I've used --speed 10. Is there something else I can do speed up the compression? 

I noticed that you wrote an overview of png compression techniques. Can you recommend one that offers comparable compression to yours (10-30% bigger file size is still acceptable), but has a speed bonus?

**Comment by pornel** [comment]
If they're literally just black and white, then you may not need quantization. Try optipng or pngcrush.
