### ISSUE TITLE
Compiled with no support for color profiles. Using libpng 1.6.28.

### ISSUE THREAD

**Issue by bydbest** [pornel/pngquant#241]
We have installed pngquant with libpng 1.6.28 but it gives error that Compiled with no support for color profiles

pngquant, 2.7.2 (June 2016), by Kornel Lesinski, Greg Roelofs.
   Compiled with no support for color profiles. Using libpng 1.6.28.

**Comment by bydbest** [comment]
solved. Updated to latest version of pngquant. color profiles are supported in latest version

**Comment by bydbest** [comment]
Installed latest version of pngquant then also getting the same error.

pngquant, 2.9.1 (April 2017), by Kornel Lesinski, Greg Roelofs.
   Compiled with no support for color profiles. Using libpng 1.6.28.

**Comment by pornel** [comment]
This is not related to libpng. Color profiles are handled by lcms2. 


## Compilation without Cocoa image reader

macOS version uses Cocoa to read images. This adds support for color profiles
and other image formats as input. `./configure --without-cocoa` switches back
to libpng.


## Compilation with Little CMS 2

    ./configure --with-lcms2 && make

Enables support for ICC v2/v4 color profiles when reading images.
Requires Little CMS library available via `pgk-config` (e.g. install `liblcms2-dev`).

**Comment by ovvo20** [comment]
After executing the code:
```bash
./configure --with-lcms2 && make
```
 I encountered the following problem:
 
![image](https://github.com/user-attachments/assets/b9d8f7f4-95d1-478c-97f5-5f8b5ceaf480)

I have installed pngquant 2.17.0 with libpng 1.6.37

**Comment by kornelski** [comment]
The text you've quoted says profiles **are** supported. This is not an error.
