### ISSUE TITLE
Some "dots" on optimized images

### ISSUE THREAD

**Issue by caub** [pornel/pngquant#242]
I guess optimization comes at a price, you can see some dots in the images after they are processed with pngquant

![2017-04-16-131330_74x102_scrot](https://cloud.githubusercontent.com/assets/3134574/25070719/f2278fa4-22a6-11e7-909a-65f2f9f28501.png)
![2017-04-16-131337_54x39_scrot](https://cloud.githubusercontent.com/assets/3134574/25070721/f3c6bede-22a6-11e7-845f-d2e4cb76ac10.png)
![2017-04-16-131519_90x56_scrot](https://cloud.githubusercontent.com/assets/3134574/25070722/f5390dda-22a6-11e7-84cf-310cdce86a63.png)

**Comment by jibsen** [comment]
You could try the `--nofs` option to disable dithering.

**Comment by caub** [comment]
Nice, interesting

**Comment by pornel** [comment]
Could you share the full image?

**Comment by caub** [comment]
Yes 
![alientemplates](https://cloud.githubusercontent.com/assets/3134574/25087280/f3297922-236d-11e7-9210-5dbbbf47e3df.png)

**Comment by pornel** [comment]
Thanks. 

In this case the image has too many gradients/shades of colors, so the dithering seems correct, and `--nofs` is indeed the solution.

**Comment by winnchen** [comment]
slove my problem

**Comment by winnchen** [comment]
solve my problem
