### ISSUE TITLE
above 2.7.2 gives error Wrote palette index exceeding num_palette

### ISSUE THREAD

**Issue by bydbest** [pornel/pngquant#243]
upto 2.7.2 pngquant works fine with libpng 1.6.28. any pngquant above 2.7.2 gives error

  error: Wrote palette index exceeding num_palette (libpng failed)
Segmentation fault (core dumped)

**Comment by pornel** [comment]
Does it happen with every image?

What options do you use when converting images?

**Comment by bydbest** [comment]
i tried one png image and got the same error with version 2.9 and 2.8 then installed 2.72 and it works without any issue
Installing lcms2 will improve quality of compressed images ??

**Comment by pornel** [comment]
Installation of lcms2 is required, but not sufficient to add support to pngquant. You also have to create your own build of pngquant with lcms2 enabled.

Please test it with the latest version from master, and test with multiple images. Please share what configure flags you've used and result of the configure script.

Make sure you're not using system pngquant package. Best to uninstall it just in case.

If the problem happens only with some images, please attach them to the bug report.

**Comment by Hinidu** [comment]
Hi! I'm getting the same error for some images in batch mode on Windows. I've installed pngquant 2.8.1 using chocolatey and checked that it is the same as the binary from the official website.

**Comment by pornel** [comment]
Yes, you will get this error in all versions between 1.8 and 2.9.1.

**Comment by Hinidu** [comment]
Can I find compiled version of the newer version for Windows somewhere? On the official site I see only 2.8.1.

**Comment by pornel** [comment]
Sorry, compiling programs for Windows is such a mess it makes me want to cry, so I rely on others to provide Windows binaries from time to time.

**Comment by Hinidu** [comment]
I understand 😢 Perhaps I could try to do that myself. I will notify you if my attempt will be successful.

**Comment by Hinidu** [comment]
Is it possible to build pngquant with lcms2 or openmp on Windows? And what are the pros and cons of them?

**Comment by pornel** [comment]
With lcms2 you get color profile support, and with openmp it's faster on multicore machines.

**Comment by Hinidu** [comment]
I've built pngquant from msvc branch using instructions from INSTALL (luckily without any problem 😮).
But this branch doesn't have the latest fixes from master branch so I'm still getting "Wrote palette index exceeding num_palette (libpng failed)" errors.
I can try to make pull requests to update msvc branch or will you do it yourself?

**Comment by Hinidu** [comment]
By the way in the new version some other problems are fixed (for example the loss of IEND chunk in batch mode sometimes).

**Comment by Hinidu** [comment]
I've created PR for libimagequant https://github.com/ImageOptim/libimagequant/pull/5.
If I understand correctly it needs to be merged to allow me create the PR using updated libimagequant to pngquant itself.

**Comment by jibsen** [comment]
Just wanted to note that I keep builds with lcms2 and OpenMP at https://github.com/jibsen/pngquant-winbuild (though I haven't updated for 2.9.1 yet). If you want to build on Windows using mingw-w64 you can use that.

**Comment by Hinidu** [comment]
@jibsen Thanks for the tip. I still can't build pngquant with OpenMP support because my local isntallation of gcc doesn't support it. But maybe it will be more performant to leave my build without OpenMP and run many instances in parallel.
Also I don't know whether I need lcms2 support or not.

**Comment by Hinidu** [comment]
@pornel I have built the latest version of pngquant including https://github.com/pornel/pngquant/pull/249 for Windows but without OpenMP and lcms2 support. I can publish this binary somewhere if you need it.
