### ISSUE TITLE
PNG image getting corrupt 

### ISSUE THREAD

**Issue by rhastantram** [pornel/pngquant#246]
I am seeing an issue with the following image (green color is getting mapped to grey at the top), this is the command line used:
pngquant --speed 8 orig.png -o opt.png

![orig](https://cloud.githubusercontent.com/assets/13951983/25507587/c68b9ac0-2b61-11e7-9c3d-87e01604acaa.png)
![opt](https://cloud.githubusercontent.com/assets/13951983/25507595/d06a53d8-2b61-11e7-9c6a-8831cf9af5cd.png)

Any pointers ?

**Comment by pornel** [comment]
I'm unable to reproduce it in the latest version

**Comment by rhastantram** [comment]
@pornel Thanks a bunch, i was using 2.4.1. It doesn't happen with latest version 2.9.1.
