### ISSUE TITLE
Add --with-zlib configure option

### ISSUE THREAD

**Issue by Roy-Orbison** [pornel/pngquant#247]
Can you enable statically compiled zlib to be used, as per [this patch](http://stackoverflow.com/a/42647449)?

**Comment by pornel** [comment]
I'm reluctant to do so. It's fiddly to support it properly, and I don't see the benefit. Unlike libpng, zlib is usually fine on various distributions. If you want completely static executable, then that won't be enough - you'd need to to something with libc, too.
