### ISSUE TITLE
Fully-transparent to semi-transparent

### ISSUE THREAD

**Issue by matjazu** [pornel/pngquant#248]
When lowering the number of colors on fully transparent PNG images I start getting fully-transparent pixels as semi-transparent. Currently, this is present on all images that I tried on.

Example:
[Original image](http://shrani.si/f/e/La/2fIlpxM9/pineapple-original.png) _fully-transparent_
[256 colors image](http://shrani.si/f/3j/3W/2we1YIfj/pineapple-256.png) _fully-transparent_
[30 colors image](http://shrani.si/f/3v/qd/2MGRgWbY/pineapple-30.png) _semi-transparent_

The change from fully to semi-transparent pixels depends on an image and does not always come at the same number of colors. 

Is this expected behavior? Is there a way to prevent this?

**Comment by pornel** [comment]
I can't reproduce it in version 2.9. Maybe you have old pngquant?

**Comment by matjazu** [comment]
I am using latest 2.9.1 (April 2017) pngquant compiled on my Debian Jessie with static libpng-1.6.29 and static zlib 1.2.11 But when I use official old 2.3.0 (July 2014) from Debian repo, I don't have this issues. Is it possible that latest libpng or zlib are the reason for this issue?

**Comment by pornel** [comment]
No, libpng/zlib shouldn't affect it.

Default build of 2.9.1 (3b84622f74a6073d8cda1879670dececcfbfac1d)

```sh
./pngquant 30 pineapple-original.png
```

gives me this:

![pineapple-original-fs8](https://cloud.githubusercontent.com/assets/72159/26059647/6ad2be62-397a-11e7-8ef3-0428dba1728d.png)

**Comment by matjazu** [comment]
I narrowed the issue down to boost variable inside lib/pam.c file.

lib/pam.c
`boost = 10;`_([line 48](https://github.com/ImageOptim/libimagequant/blob/5c9ee29e9c2267826e840ba3328af4da8108a6ca/pam.c#L48))_ 

If I remove this line that was introduced with commit [fb571df](https://github.com/pornel/pngquant/commit/fb571dfc74d37598414d27a7105acce1c4f43795) issue disappears. Is there anything that you / we can do about this? If we remove this what are the consequences?

**Comment by pornel** [comment]
I'm surprised. That sounds completely backwards. That change was meant to *prevent* the issue you're seeing, not cause it. 

If you remove that `boost = 10` line, you'll get the value for opaque pixels, which is in 0.5-1.5 range, which is much lower, and would make the rest of the algorithm place less importance on preserving the transparency.

How are you building it? What settings do you use when you run it? I can't reproduce the problem with your image.

**Comment by matjazu** [comment]
I also figure it out that this transparency issue is somehow connected to the --speed option too (if I don't remove boost variable of course):
_(case of pineapple image)_
- at speed 8 issue starts at color option around 100 and lower (lower we go, more visible the issue gets)
- at speed 7 issue starts at color option around 16 and lower
- at speed 6 issue starts at color option around 14 and lower 
- at speed 5 issue starts at color option around 6 and lower 


I run pngquant with the following options:
```
pngquant 30 --speed=8 --floyd=1 -
```


Meanwhile I build it like this:
- clone the whole pngquant repo
- download both libpng & zlib as subfolder inside pngquant folder
- compile first libpng & zlib and then also pngquant

Output of compiler:
```
matjaz:~/utils/pngquant_make/pngquant$ ./configure && make

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: static (1.6.29)
      zlib: static
     lcms2: no

gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o pngquant.o pngquant.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o rwpng.o rwpng.c
make -C lib static
make[1]: Entering directory '/home/matjaz/utils/pngquant_make/pngquant/lib'
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o pam.o pam.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o mediancut.o mediancut.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o blur.o blur.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o mempool.o mempool.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o kmeans.o kmeans.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o nearest.o nearest.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast   -c -o libimagequant.o libimagequant.c
ar rv libimagequant.a pam.o mediancut.o blur.o mempool.o kmeans.o nearest.o libimagequant.o
r - pam.o
r - mediancut.o
r - blur.o
r - mempool.o
r - kmeans.o
r - nearest.o
r - libimagequant.o
make[1]: Leaving directory '/home/matjaz/utils/pngquant_make/pngquant/lib'
gcc pngquant.o rwpng.o lib/libimagequant.a -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./libpng-1.6.29 -I./zlib-1.2.11 -fexcess-precision=fast ./libpng-1.6.29/.libs/libpng16.a ./zlib-1.2.11/libz.a -lm -o pngquant
```

Is there anything you can to prevent this issue at high speed?

**Comment by pornel** [comment]
Ah, at speed 8 it's totally expected. Just don't use it if you want high quality palette.

**Comment by matjazu** [comment]
OK, tnx.
