### ISSUE TITLE
Size issue when using floyd dithering and low number of colors 

### ISSUE THREAD

**Issue by matjazu** [pornel/pngquant#251]
Hey,

I noticed that when I optimize certain images with --floyd enabled (value from 0.1 to 1) and a low number of colors I sometimes get bigger file size than when using a higher number of colors.

Example 1 ([source image 1](https://drive.google.com/open?id=0BwD6TYn1d3xsSkV0QXpmcmZoYlU))
```
pngquant 20  --speed=7 --floyd=1 --strip       file size: 12,1Kb
pngquant 156 --speed=7 --floyd=1 --strip       file size: 10,3Kb
pngquant 256 --speed=7 --floyd=1 --strip       file size: 12,6Kb
```

Example 2 ([source image 2](https://drive.google.com/open?id=0BwD6TYn1d3xsSkRiendTbnh2Slk))
```
pngquant 20  --speed=7 --floyd=1 --strip       file size: 7,7Kb
pngquant 40  --speed=7 --floyd=1 --strip       file size: 6,1Kb
pngquant 256 --speed=7 --floyd=1 --strip       file size: 11,7Kb
```

Example 3 ([source image 3](https://drive.google.com/open?id=0BwD6TYn1d3xsU29RRWtfWnJwcTQ))
```
pngquant 20  --speed=7 --floyd=1 --strip       file size: 6,5Kb
pngquant 115 --speed=7 --floyd=1 --strip       file size: 3,3Kb
pngquant 256 --speed=7 --floyd=1 --strip       file size: 5,8Kb
```

If I lower Floyd value the behavior is still present just size differences are little smaller. I'm using pngquant 2.9.1.

Is there something that we can do about this or is this expected behavior?

**Comment by pornel** [comment]
This is expected, especially in simple images. Runs of solid color compress perfectly. OTOH dithering is like noise, so it doesn't compress.

**Comment by matjazu** [comment]
Thank you for explaining.
