### ISSUE TITLE
pngquant command doesn't work from php but works fine when the same is executed from shell

### ISSUE THREAD

**Issue by lensonsaldanha** [pornel/pngquant#254]
> pngquant --quality=65-80 test.png --output test-small.png

This command works fine from shell and I get the required output

When the same is executed from php, it doesn't work(It do not create a new image : test-small.png)

Here is my Php code

>   shell_exec('pngquant --quality=65-80 test.png --output test-small.png'); 

Other Shell commands execute well from php.(ex: ls, whoami)

Note: I delete the test-small.png(if exists) before I check my php script

**Comment by pornel** [comment]
Please make sure `pngquant` is in server's `PATH` or use an aboslute path to the pngquant executable.

If you're on a Mac, then it may be broken by `DYLD_LIBRARY_PATH` #240

**Comment by lensonsaldanha** [comment]
I'm on Centos 
How do I use an aboslute path to the pngquant executable?
This is the path where it is installed

> which pngquant
> /usr/local/bin/pngquant

**Comment by lensonsaldanha** [comment]
I got it working with absolute path.
Thanks for your quick reply.

Here is the working php code for my problem

shell_exec('/usr/local/bin/pngquant --quality=65-80 test.png --output test-small.png');

**Comment by borzenkovdev** [comment]
@lensonsaldanha  Hello! Thansk for solution
I got it working with absolute path too.
