### ISSUE TITLE
Is an "in-place" modifier in the roadmap?

### ISSUE THREAD

**Issue by queirozfcom** [pornel/pngquant#255]
I (an, I expect, many others) would benefit from some flag or modifier that performs compression in place, such as `sed`'s `-i` modifier. 

I believe it should be a simple fix - is that in the roadmap?

**Comment by pornel** [comment]
There's a hack via `--ext .png -f`, but I don't plan to expand it. The conversion is lossy, so it should be treated as an export operation, not a (destructive) in-place optimization.
