### ISSUE TITLE
pngquant 2.10.1 release archives?

### ISSUE THREAD

**Issue by rcanavan** [pornel/pngquant#256]
I may be missing something, but I can't locate a complete pngquant 2.10.1 release archive. The releases downloadable on github don't include libimagequant and https://pngquant.org/releases.html only goes up to 2.10.0.

I can obviously clone the repository and checkout 2.10.1, but something more official would be appreciated.

**Comment by pornel** [comment]
Sorry for trouble. I've uploaded the archive.

**Comment by rcanavan** [comment]
Thanks.
