### ISSUE TITLE
undefined behavior in pngquant.c

### ISSUE THREAD

**Issue by asarubbo** [pornel/pngquant#258]
Visibile if compiled with -fsanitize=undefined
```
# pngquant $FILE:INPUT --quality 100 --speed 11 -o $FILE.OUTPUT
pngquant.c:546:5: runtime error: null pointer passed as argument 1, which is declared to never be null
```

**Comment by pornel** [comment]
Which version are you using?

**Comment by asarubbo** [comment]
I'm using 2.7.2 I realized now that it isn't the latest upstream.
I used 2.7.2 because is the latest I found in our repository.

**Comment by asarubbo** [comment]
It is fine with 2.10.1

**Comment by pornel** [comment]
Thanks. Good to know that these annotations are catching bugs :)
