### ISSUE TITLE
Option --strip unrecognised

### ISSUE THREAD

**Issue by CombesA** [pornel/pngquant#260]
Hey there, thanks for this tool, it's really helpful !

Alright so I don't know if it's a real isue or just me being dumb, but here's my problem : I want to compress a png, so this is the commande I use : 
`pngquant -o test/sprite32.png --quality=15-20 --strip sprite32.png`
I'm working on a script in nodeJS so I use the execSync function from 'child-process' for executing my commands
But the problem is windows is telling me that the command failed and the error is "unrecognised option '--strip'"
I don't really know what to do, I've looked for a solution but I can't find anything.

I have this other problem, which is, if I specify a number of colors like so :
`pngquant 8 -o test/sprite32.png --quality=15-20 sprite32.png`
Windows tell me that my command failed.
If I just type the command in windows command prompt, it execute well without any error, but the file is not written.

I hope you can help me with that !

**Comment by pornel** [comment]
Which version do you have? Maybe it's an old one.

**Comment by CombesA** [comment]
I've download it from your website, so I guess I have 2.10.1, though pngquant -v doesn't work.

**Comment by pornel** [comment]
`pngquant -V` should show you the version. `pngquant -v` too, it's just above all other help text.

**Comment by CombesA** [comment]
Woaw, yeah for some reasons `pngquant -V` workd but not `pngquant -v`, anyway, even if I download it from your website, I only have the 2.4.0 from April 2015.

**Comment by pornel** [comment]
Good.
