### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [pornel/pngquant#261]
Based on https://github.com/pornel/pngquant/releases/latest it's not clear to me whether 2.10.1 or 2.10.2 is the current stable release version. Could you clarify which should be in Homebrew now? Thanks!

**Comment by pornel** [comment]
The 2.10.2 only tweaks build for Rust

You're not using https://crates.io/crates/imagequant so there are no changes for yu

**Comment by ilovezfs** [comment]
@pornel ah OK! Would there be any reason for Homebrew to switch over to a rust based build now?

**Comment by pornel** [comment]
Yes, if that's not a problem for you I'd suggest switching to the Rust build. For now I support both make and Cargo, but I'd prefer to switch fully to Rust long term.

**Comment by ilovezfs** [comment]
@pornel nope, it's not a problem. We have 13 formulae other than rust itself using cargo.

**Comment by ilovezfs** [comment]
@pornel https://github.com/Homebrew/homebrew-core/pull/16543

**Comment by ilovezfs** [comment]
@pornel same question RE: 2.10.2 vs. 2.11.2

**Comment by pornel** [comment]
2.11.2 is the latest. 

When I release:

1. I create a tag in git
2. I publish on https://pngquant.org/releases.html

I do not keep https://github.com/pornel/pngquant/releases up to date, so don't pay attention to that.

**Comment by ilovezfs** [comment]
OK. Our livecheck stuff tries to honor https://github.com/pornel/pngquant/releases/latest since some upstreams are very picky about that but I'll see what I can do.

**Comment by ilovezfs** [comment]
@pornel it may be worth using the API https://developer.github.com/v3/repos/releases/#create-a-release to automate keeping https://github.com/pornel/pngquant/releases matching https://pngquant.org/releases.html

**Comment by pornel** [comment]
OK, I'll try to update that
