### ISSUE TITLE
Error: Option 'floyd' does not take an argument

### ISSUE THREAD

**Issue by tflo** [pornel/pngquant#262]
Recently I'm getting the error message "Option 'floyd' does not take an argument." from my script.

It was set to `--floyd=1`. Removing the value helps. Is this intended?

pngquant 2.10.2 from Homebrew's pngquant-2.10.2.sierra.bottle.tar.gz (Mac).

– Tom

**Comment by pornel** [comment]
This is a bug. The argument should work, but switching to a new argument parsing library removed that ability.

`1` is the default, so you can leave it off.

**Comment by pornel** [comment]
Fixed 885e8f516822c107af1435d3d87a56d4ff36ee94
