### ISSUE TITLE
Returning larger image?

### ISSUE THREAD

**Issue by Creativico** [pornel/pngquant#263]
Hi everyone! 

First of all.. thanks for the awesome tool! :) Keep up the good work!

I'm testing few images.. for example
![macbook-silver 3x-min-2 2](https://user-images.githubusercontent.com/1302157/29808272-a572c5ec-8c97-11e7-835d-4fb1d3aa4fde.png)

But when I use pngquant on it, I constantly get 10-15% increase in file size :( 

But when I try other tools I get it compressed 5-10KB ...

I tried many variations of calling..
/usr/local/bin/pngquant --speed 2 --quality 95 --force --output ...

Any ideas what I'm doing wrong? :(

Thanks!

**Comment by pornel** [comment]
Compression depends on image content. Some content may compress better in 24-bit.

Disabling dithering `--nofs` may help, but at cost of quality. You can skip these kinds of images with `--skip-if-larger` option.
