### ISSUE TITLE
macOS binary can input JPEG file but Windows binary NOT.

### ISSUE THREAD

**Issue by meowtec** [pornel/pngquant#264]
I want to input JPEG files then convert and compress them using pngquant, without other tools like ImageMagick.

on macOS, successfully:

```
pngquant test.jpg -o test.png
```

on Windows, failed with an error:

```
error: Not a PNG file (libpng failed)
error: cannot decode image
```

**Comment by pornel** [comment]
Yes, indeed. This is simply not implemented on Windows. I'm more familiar with macOS and there I was able to implement loading of any image type with a few lines. 

In any case, converting JPEG to PNG8 is unlikely to make files look better or be smaller. Try Guetzli or MozJPEG instead.
