### ISSUE TITLE
Cannot install pngquant on CentOS 7, I had installed it in prev server(CentOS 6.9)

### ISSUE THREAD

**Issue by lensonsaldanha** [pornel/pngquant#266]
Hello, I had installed pngquant in my prev server and it was working fine. I moved all my files to new server. and I'm trying to install pngquant here.
`git clone --recursive https://github.com/pornel/pngquant.git`
This downloaded files succesfully
when I do `ls` I can see pngquant directory with files inside it
I want it to be installed in /usr/local/bin
so I ran
`sudo make install`
`make: *** No rule to make target 'install'.  Stop.`
and I'm getting the above error message.
Please help

**Comment by 7snovic** [comment]
are you sure that you'd ran `make` before `make install` ?

**Comment by lensonsaldanha** [comment]
I tried that too, and I got this:
```
make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by lensonsaldanha** [comment]
Nevermind, I just did this and it worked for me
`yum install pngquant`

**Comment by futureweb** [comment]
I got the same Problems on Centos/RHEL 7 when trying to compile latest GIT Version:

```
server pngquant# make
./configure

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
imagequant: build static
    libpng: shared (1.5.13)
      zlib: shared (1.2.7)
     lcms2: shared (2.6)

gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng15       -DUSE_LCMS=1 -fexcess-precision=fast   -c -o pngquant.o pngquant.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng15       -DUSE_LCMS=1 -fexcess-precision=fast   -c -o pngquant_opts.o pngquant_opts.c
gcc -fno-math-errno -funroll-loops -fomit-frame-pointer -Wall -std=c99 -I. -O3 -DNDEBUG -DUSE_SSE=1 -msse -mfpmath=sse -Wno-unknown-pragmas -I./lib -I/usr/include/libpng15       -DUSE_LCMS=1 -fexcess-precision=fast   -c -o rwpng.o rwpng.c
( cd './lib'; ./configure '--quiet'  )
warning: unknown switch --quiet (see ./configure --help for the list)

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no

make: *** No rule to make target `lib/Cargo.toml', needed by `lib/libimagequant.a'.  Stop.
```

Andreas Schnederle-Wagner

**Comment by futureweb** [comment]
info: lib Folder wasn't updated -that's why the Error occured ... after a recursive GIT clone it's working ... :)

**Comment by pascaloliv** [comment]
Same issue on CentOS 7.4 when trying to install pngquant. 
I tried to install `libpng-devel` but it did nothing more... 

Any news on this issue ?

```
> pngquant-bin@3.1.1 postinstall /srv/app/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/srv/app/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by sergiomb2** [comment]
> yum install pngquant

yeah I maintain package pngquant in epel , the version is 2.7.2 , since 2.10 you need build first libimagequant, https://github.com/ImageOptim/libimagequant .

anyway from where came node.js ?

**Comment by pascaloliv** [comment]
This comment helped me to build `pngquant`.
https://github.com/kornelski/pngquant/issues/231#issuecomment-289265273

For your information, the following one for `mozjpeg` if you have error to compile from source too.
https://github.com/imagemin/imagemin-mozjpeg/issues/1#issuecomment-52784569

**Comment by kimek** [comment]
## RHEL/CentOS 7 64-Bit EPEL ##
wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
yum repolist
yum install pngquant
