### ISSUE TITLE
Option to preserve original timestamp fields, output is not deterministic

### ISSUE THREAD

**Issue by joshfriend** [pornel/pngquant#269]
The tool currently sets `tIME` to the time when the output is generated, instead of keeping the original image's time. This is causing the output of the tool to be non-deterministic. 

I am generating compressed versions of website assets during my build process. The output files are identical when compared with imagemagick, the only difference is the timestamp fields in the PNG header ([example](https://www.diffchecker.com/5NBlWeWu)). This is making it impossible for the AWS deployment portion to figure out that the file has not changed (_technically_ it has, but hopefully you see my point) and is forced to upload all PNG files every time because the md5 sums do not match.

I would like to have some way to ensure that the output is deterministic!

**Comment by pornel** [comment]
pngquant is not adding the time chunk. It's probably just copied from the input file, which you can disable with `--strip`.

**Comment by joshfriend** [comment]
Thanks, it looks like you are correct! Sorry for my confusion.
