### ISSUE TITLE
Invalid generated png

### ISSUE THREAD

**Issue by alpha0010** [pornel/pngquant#270]
Invalid generated png:
[Input](http://pasteall.org/pic/index.php?id=119045)
[Output](http://pasteall.org/pic/index.php?id=119046)
`pngquant --speed 1 pew102-test.png`

**Comment by pornel** [comment]
Are you using Debian stable? pngquant will generate broken images if it's compiled with the outdated libpng 1.2.

The bug has been fixed *many years ago* in libpng 1.4.

**Comment by alpha0010** [comment]
I am using https://packages.ubuntu.com/trusty/pngquant .  I will look into self-building it, or see if it is possible to upgrade my OS.  (This is a work environment...)
