### ISSUE TITLE
Convert to 8-bits only.

### ISSUE THREAD

**Issue by DavisDev** [pornel/pngquant#271]
Hello!

Is there a way to set the maximum compression?

I always need to compress to 8b, but sometimes when an image does not have many colors, it compresses them to 1b, 2b, 4b, which results in compatibility error.

Some function that allows such configuration, or flag.

Thanks for the help!

**Comment by pornel** [comment]
What is it incompatible with? You should probably fix whatever PNG reader you're using, because the PNG standard requires support for 1/2/4 bpp.

You can change `sample_depth` in `rwpng.c`

**Comment by DavisDev** [comment]
Now work good!
Thanks!
