### ISSUE TITLE
Setting parameter speed to 0 (zero) works

### ISSUE THREAD

**Issue by na-oma** [pornel/pngquant#272]
Dunno if a feature or bug, but in the ongoing hunt for lower speed and more savings, i tried
`pngquant --speed 0 abc.png`
It works, sometimes it produces an image like `--speed 11`, sometimes a worse image.
I guess it skips the check in https://github.com/pornel/pngquant/blob/885e8f516822c107af1435d3d87a56d4ff36ee94/pngquant.c#L294
and does something weird.
Changing this may break things.
But maybe speed 0 it is the path to even lower filesizes ;)

**Comment by pornel** [comment]
Speed 0 is identical to leaving the default speed (3). Unfortunately there's no magic bullet here.
