### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by fangqiao** [pornel/pngquant#274]
Hi, I am testing pngquant. 

I found out in most cases the output quality is excellent. Thanks for the great product.

But occasionally there is a change of bright color, especially when it is very big text.

Below is a test sample. Conversion command is: `pngquant -f --quality 90-100 --ext 90-100.png WX20171106-162743@2x.png`

You can notice the difference of text color. By the way, I tried it on tinypng.com. The text color remained unchanged.

Original image:

<img width="867" alt="wx20171106-162743 2x" src="https://user-images.githubusercontent.com/17473990/32760552-610eaf7a-c8b4-11e7-857f-03e3ae82a2a2.png">

Output:
<img width="867" alt="wx20171106-162743 2x90-100" src="https://user-images.githubusercontent.com/17473990/32760548-5d02239e-c8b4-11e7-9538-d778e7a72413.png">

Thanks,

**Comment by jibsen** [comment]
Your original image contains a color profile, do you use a version of pngquant compiled with Little CMS?

When I process the image with a pngqant with color profile support it seems to produce the correct yellow color.

**Comment by fangqiao** [comment]
I compiled directly from git on Centos, using ./configure & make. Can you point me to the document about compilation with color profile support? Or if no documentation for it, can you tell me how to do it? Thanks

**Comment by fangqiao** [comment]
I have figured it out by reading the configure script. Need to run ./configure --with-lcms2. And the new version's out has correct color. Thanks.
