### ISSUE TITLE
If the path contains Chinese characters, it will prompt that the file cannot be read

### ISSUE THREAD

**Issue by zhaixiaowai** [pornel/pngquant#275]
pngquant --force  "e:\我的设备\下载区\pngquant-windows\pngquant\1.png" --ext ".min.png" --quality 50-90  --speed 1
  error: cannot open e:\我的设备\下载区\pngquant-windows\pngquant\1.png for reading

**Comment by pornel** [comment]
It is a known problem. Duplicate of #265
