### ISSUE TITLE
why  the compression is not good on NEW version(2.11.2)

### ISSUE THREAD

**Issue by jet6666** [pornel/pngquant#278]
sample image:

![glory_item](https://user-images.githubusercontent.com/3762571/33252701-ade15764-d37a-11e7-93a7-9c9d057d9949.png)

just use default parameters:

> pngquant  glory_item.png:
there is no different between two images.

But I use old version( 1.8.1  , from pnggoo )  , It can coverted to 5KB.

**Comment by pornel** [comment]
The image you've attached is already converted. Can you provide the original?

**Comment by jet6666** [comment]
This image is orginal :

   `https://user-images.githubusercontent.com/3762571/33252701-ade15764-d37a-11e7-93a7-9c9d057d9949.png`



you can try it

**Comment by pornel** [comment]
This image has less than 256 colors already, so there's nothing for pngquant to do with it.

**Comment by jet6666** [comment]
I don't think so ,It maybe depend on the image  dimension (width and height)

I have tried many icons on my project , they are all have less compression.
[aaa.zip](https://github.com/pornel/pngquant/files/1512419/aaa.zip)

 
thanks for your replay!

**Comment by pornel** [comment]
Thanks!

So there are two differences:

1. The new pngquant is able to preseve metadata, and Adobe Photoshop CC added a lot of hidden garbage to the file. Use `--strip` option to remove it.

2. Apart from that image from the new version is 1% larger, but has 20% better quality score (measured with DSSIM). You can use options like `--quality=70` && `--floyd=0.2` to lower the quality if the default quality is more than you need.
