### ISSUE TITLE
Large amount of dithering in even colours with pngquant 2.0 (master)

### ISSUE THREAD

**Issue by rolftimmermans** [pornel/pngquant#40]
Hello!

When trying the latest version of pngquant (from master), I noticed that in some cases an even colour is being dithered. This does not happen in 1.8.3. It has an extremely negative effect on the image size. In this specific example the image size of the 2.0-optimised version is almost 3 times larger than the 1.8.3-optimised version!

Here is an example of the dithering in 2.0:
![example-dither](https://f.cloud.github.com/assets/78237/798053/8122b31a-ed58-11e2-81d9-d525f39c2499.jpg)

Here is the result from 1.8.3 (51 KB).
![example-fs8-1 8 3](https://f.cloud.github.com/assets/78237/798044/3aa128a4-ed58-11e2-85cb-8951355941e7.png)

Here is the result from 2.0 (138 KB).
![example-fs8-2 0](https://f.cloud.github.com/assets/78237/798046/3ae5dee0-ed58-11e2-9309-f8871c240631.png)

Here is the original (187 KB).
![example-orig](https://f.cloud.github.com/assets/78237/798045/3ae0829c-ed58-11e2-8c5b-70e95493e63a.png)

The images were produced with `pngquant 256 example.png`.

Do you have any idea what the cause is? Is this intended behaviour with 2.0, or is it simply not ready yet?

**Comment by pornel** [comment]
I think it's been fixed since. I can't reproduce distortions on these two images.
