### ISSUE TITLE
liq_quantize_image interface

### ISSUE THREAD

**Issue by benkasminbullock** [pornel/pngquant#70]
The interface for this function seems not ideal to me, I just sent up a testing version of my perl module to CPAN and I got a lot of errors:

http://www.cpantesters.org/distro/I/Image-Quantize.html?oncpan=1&distmat=1&version=0.00_02

Looking at the error reports

http://www.cpantesters.org/cpan/report/6b710f50-9a94-11e3-9f77-e2945d7e0655

it failed like this:

Quantize failed at /tmp/loop_over_bdir-17583-Mm4cSJ/Image-Quantize-0.00_01-n1w5bO/blib/lib/Image/Quantize/PNG.pm line 26.

This is the result of getting a NULL back from liq_image_quantize. But I have no idea what the problem was within liq_image_quantize. Could the interface be changed so that some kind of error is accessible?

**Comment by pornel** [comment]
There's a new `liq_image_quantize` that exposes the error.
