### ISSUE TITLE
Error on Ubuntu 12.04 server 

### ISSUE THREAD

**Issue by fortinux** [pornel/pngquant#72]
Could you help with this error please? (There were no errors at installation)

pngquant Firefox_wallpaper.png
pngquant: mempool.c:40: mempool_create: Assertion `!((uintptr_t)(_mptr + (_mptr)->used) & 15UL)' failed.

Thanks

**Comment by wshxbqq** [comment]
Sees Like this problem will only appear on the 32 bit version of Linux
